"use client";
import { useState } from "react";

type Extraction={professional:Record<string,string|number>;certifications:any[];equipment:any[];industries:any[];codes_standards:any[];languages:any[];improvements:any[];review_notes:string[]};
export default function SmartUpload(){
 const [files,setFiles]=useState<File[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [data,setData]=useState<Extraction|null>(null); const [approved,setApproved]=useState<Record<string,boolean>>({});
 async function extract(){setLoading(true);setError("");const fd=new FormData();files.forEach(f=>fd.append("files",f));try{const r=await fetch("/api/inspector-onboarding/extract",{method:"POST",body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||"Extraction failed");setData(j.extraction)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 const rows=data?[...Object.entries(data.professional).filter(([,v])=>v!==""&&v!==0).map(([k,v])=>({key:`p-${k}`,label:k.replaceAll("_"," "),value:String(v),confidence:1,evidence:"Extracted from uploaded documents"})),...data.certifications.map((x,i)=>({key:`c-${i}`,label:x.name,value:[x.certificate_number,x.expires_on&&`expires ${x.expires_on}`].filter(Boolean).join(" · "),confidence:x.confidence,evidence:x.evidence})),...data.equipment.map((x,i)=>({key:`e-${i}`,label:x.name,value:x.years_experience?`${x.years_experience} years`:"Experience identified",confidence:x.confidence,evidence:x.evidence})),...data.industries.map((x,i)=>({key:`i-${i}`,label:x.name,value:x.years_experience?`${x.years_experience} years`:"Experience identified",confidence:x.confidence,evidence:x.evidence}))]:[];
 return <section style={{marginTop:18,padding:18,border:"1px solid #cbd5e1",borderRadius:14,background:"#fff"}}><h3 style={{marginTop:0}}>Live document extraction</h3><p style={{color:"#64748b"}}>Upload PDF certificates/CVs or JPG/PNG credential images. AI extracts facts, but you approve them before anything is used.</p><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png" onChange={e=>{setFiles(Array.from(e.target.files||[]));setData(null)}}/><div style={{display:"flex",gap:8,flexWrap:"wrap",margin:"10px 0"}}>{files.map(f=><span key={f.name} style={{padding:"5px 8px",background:"#f1f5f9",borderRadius:999,fontSize:12}}>{f.name}</span>)}</div><button disabled={!files.length||loading} onClick={extract} style={{padding:"10px 14px",border:0,borderRadius:9,background:"#0f172a",color:"white",fontWeight:800}}>{loading?"Reading your documents…":"Build my profile from these documents"}</button>{error&&<p style={{padding:10,background:"#fef2f2",color:"#991b1b",borderRadius:8}}>{error}</p>}{data&&<div style={{marginTop:18}}><h3>Review extracted profile</h3>{rows.map(r=><div key={r.key} style={{display:"grid",gridTemplateColumns:"1fr auto",gap:10,padding:"10px 0",borderBottom:"1px solid #e2e8f0"}}><div><strong style={{textTransform:"capitalize"}}>{r.label}</strong><div>{r.value}</div><small style={{color:"#64748b"}}>{r.evidence} · {Math.round((r.confidence||0)*100)}% confidence</small></div><button onClick={()=>setApproved(v=>({...v,[r.key]:!v[r.key]}))} style={{height:"max-content",padding:"7px 10px",border:"1px solid #cbd5e1",borderRadius:8,background:approved[r.key]?"#dcfce7":"white",color:approved[r.key]?"#166534":"#0f172a",fontWeight:800}}>{approved[r.key]?"Approved ✓":"Approve"}</button></div>)}{data.review_notes.length>0&&<div style={{marginTop:14,padding:12,background:"#fffbeb",borderRadius:10}}><strong>Please review</strong>{data.review_notes.map((n,i)=><div key={i}>• {n}</div>)}</div>}{data.improvements.length>0&&<div style={{marginTop:14}}><h3>Free profile improvements</h3>{data.improvements.map((x,i)=><div key={i} style={{padding:11,marginTop:7,border:"1px solid #dbeafe",background:"#eff6ff",borderRadius:10}}><strong>{x.title}</strong><div>{x.reason}</div><small>{x.suggested_text}</small></div>)}</div>}<p style={{fontWeight:800,color:"#166534"}}>{Object.values(approved).filter(Boolean).length} of {rows.length} extracted items approved.</p></div>}</section>
}
