import Link from "next/link";

const contracts = [
  {client:"Atlas LNG Development", contract:"Gulf Coast MSA", status:"Active", coverage:"US Gulf Coast · rotating/static equipment", budget:"USD 620k", awarded:"USD 428k", billed:"USD 301k", availability:"14 / 32 resources", terms:"Net 45", rate:"USD 1,080/day", package:"Mileage capped at $85/day · lodging separate · travel time 50% · OT/weekend +25% · report time included"},
  {client:"Orion Energy Projects", contract:"Middle East Vendor Surveillance", status:"Active", coverage:"UAE · Qatar · Saudi Arabia", budget:"USD 510k", awarded:"USD 344k", billed:"USD 266k", availability:"11 / 27 resources", terms:"Net 30", rate:"USD 1,240/day", package:"Per diem included · local travel separate · airfare at cost · mobilization capped · OT +20%"},
  {client:"Meridian Process Systems", contract:"European Valve Framework", status:"Active", coverage:"Italy · Germany · Netherlands", budget:"EUR 390k", awarded:"EUR 247k", billed:"EUR 201k", availability:"8 / 21 resources", terms:"Net 45", rate:"EUR 980/day", package:"Local travel included · lodging separate · airfare capped · weekend +25% · report time included"},
];

const performance = [
  ["Atlas LNG Development", "82%", "$428k", "96%", "2.1%", "6.2 days"],
  ["Orion Energy Projects", "76%", "$344k", "94%", "3.4%", "7.0 days"],
  ["Meridian Process Systems", "71%", "€247k", "98%", "1.8%", "5.4 days"],
];

export default function AgencyCommercialsDemoPage() {
  return <main className="shell">
    <div className="notice"><strong>Demo Mode</strong> — fictional contracts, rates, budgets and performance only. No production billing, compensation, credentials or client data are used.</div>
    <header><div><span className="eyebrow">Agency Workspace · commercial review</span><h1>Contracts, Commercials & Analytics</h1><p>See client relationships, contract coverage, resource capacity, commercial packages and operational performance together while preserving agency/source provenance.</p></div><Link className="back" href="/demo/agency">← Agency Workspace</Link></header>

    <section className="kpis" aria-label="Agency commercial KPIs"><article><b>12</b><span>Active client agreements</span></article><article><b>$1.8M</b><span>Awarded YTD</span></article><article><b>$1.31M</b><span>Billed YTD</span></article><article><b>78%</b><span>Resource utilization</span></article><article><b>96%</b><span>On-time reports</span></article><article><b>88%</b><span>NCR closure ≤ 7 days</span></article></section>

    <section className="card"><div className="sectionHead"><div><h2>Client contracts & commercial packages</h2><p>Commercial terms travel with the agency sourcing channel; the same inspector may have different eligible agency packages without becoming duplicate people.</p></div><span className="pill">Synthetic contract portfolio</span></div>
      <div className="tableWrap"><table><thead><tr><th>Client / contract</th><th>Coverage</th><th>Budget / awarded / billed</th><th>Capacity</th><th>Base rate</th><th>Payment</th><th>Commercial package</th></tr></thead><tbody>{contracts.map(c=><tr key={c.contract}><td><b>{c.client}</b><small>{c.contract} · {c.status}</small></td><td>{c.coverage}</td><td><b>{c.budget}</b><small>{c.awarded} awarded · {c.billed} billed</small></td><td>{c.availability}</td><td>{c.rate}</td><td>{c.terms}</td><td className="wrap">{c.package}</td></tr>)}</tbody></table></div>
      <p className="fine">Packages model currency, payment terms, mileage, per diem/meals, local travel, travel time, lodging, airfare, mobilization, overtime/weekend premiums, report time and modeled taxes/fees. Client notes can be attached to a commercial channel. This demo does not execute billing or change inspector compensation.</p>
    </section>

    <div className="grid"><section className="card"><h2>Revenue & billing status</h2><div className="bars"><div><span>Atlas LNG</span><progress max="620" value="428"/><b>69% awarded</b></div><div><span>Orion Energy</span><progress max="510" value="344"/><b>67% awarded</b></div><div><span>Meridian Process</span><progress max="390" value="247"/><b>63% awarded</b></div></div><p className="fine">Budget consumption is synthetic. Billing status is informational only; no payment rail or invoice execution is connected.</p></section>
      <section className="card"><h2>Portfolio mix</h2><ul className="mix"><li><b>46%</b> Gulf Coast / North America</li><li><b>31%</b> Middle East</li><li><b>17%</b> Europe</li><li><b>6%</b> West Africa / other</li></ul><p>Filter concepts: client · contract · geography · commodity · project · relationship type · inspector · source channel.</p></section></div>

    <section className="card"><div className="sectionHead"><div><h2>Client & contract performance</h2><p>Operational analytics connect utilization, revenue, report timeliness and quality outcomes without rewriting historical source attribution.</p></div><span className="pill">90-day synthetic view</span></div>
      <div className="tableWrap"><table><thead><tr><th>Client</th><th>Utilization</th><th>Awarded value</th><th>On-time reports</th><th>NCR rate</th><th>Avg. NCR closure</th></tr></thead><tbody>{performance.map(r=><tr key={r[0]}>{r.map((v,i)=><td key={v}>{i===0?<b>{v}</b>:v}</td>)}</tr>)}</tbody></table></div>
    </section>

    <section className="card"><h2>Commercial provenance</h2><div className="provenance"><article><b>Agency-specific search</b><p>When a client selects an inspector from this agency pool, the opportunity is attributed to this agency and its applicable contract/commercial channel.</p></article><article><b>Broad marketplace search</b><p>One inspector identity can expose multiple eligible agency channels. The selected commercial channel is recorded; upload order does not create ownership.</p></article><article><b>Historical audit</b><p>Ending an affiliation does not rewrite previously awarded work, source-of-engagement, contract, rate package or report history.</p></article></div></section>

    <p className="fine boundary">Synthetic/demo presentation only. Production affiliation verification, matching/eligibility enforcement, authorization, billing/payment, legal execution, compensation and API credentials remain review-gated.</p>
    <style>{`*{box-sizing:border-box}.shell{max-width:1450px;margin:0 auto;padding:22px;color:#0f172a}.notice{padding:10px 14px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:10px;color:#1e40af;margin-bottom:16px}header,.sectionHead{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}h1{font-size:2rem;margin:5px 0}h2{font-size:1.05rem;margin-top:0}p{color:#475569}.eyebrow{text-transform:uppercase;letter-spacing:.08em;font-size:.7rem;font-weight:800;color:#2563eb}.back{text-decoration:none;color:#1d4ed8;font-weight:700;padding:8px}.kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:18px 0}.kpis article,.card{border:1px solid #e2e8f0;border-radius:14px;background:#fff;padding:16px}.kpis b{display:block;font-size:1.35rem}.kpis span{font-size:.78rem;color:#64748b}.card{margin-bottom:14px}.pill{background:#f1f5f9;border-radius:999px;padding:5px 9px;font-size:.72rem;font-weight:700;white-space:nowrap}.tableWrap{overflow:auto}table{border-collapse:collapse;width:100%;font-size:.8rem}th,td{text-align:left;padding:10px;border-top:1px solid #e2e8f0;vertical-align:top;white-space:nowrap}th{color:#64748b}td small{display:block;color:#64748b;margin-top:4px}.wrap{white-space:normal;min-width:270px}.fine{font-size:.76rem;color:#64748b}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.bars{display:grid;gap:12px}.bars div{display:grid;grid-template-columns:130px 1fr 100px;gap:8px;align-items:center;font-size:.8rem}.bars progress{width:100%}.mix{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding-left:18px;color:#475569}.provenance{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.provenance article{padding:13px;border:1px solid #e2e8f0;border-radius:10px;background:#f8fafc}.provenance p{font-size:.82rem}.boundary{padding:12px;background:#fffbeb;border:1px solid #fde68a;border-radius:10px}@media(max-width:950px){.kpis{grid-template-columns:repeat(3,1fr)}.grid,.provenance{grid-template-columns:1fr}}@media(max-width:620px){header,.sectionHead{display:block}.kpis{grid-template-columns:1fr 1fr}.bars div{grid-template-columns:1fr}.mix{grid-template-columns:1fr}}`}</style>
  </main>;
}
