"use client";

import { useMemo, useState } from "react";
import ClientWorkspaceSidebar from "@/components/ClientWorkspaceSidebar";
import { DEMO_INSPECTIONS, type DemoInspection } from "@/lib/clientDemoInspections";

type FilterKey="project"|"projectType"|"country"|"commodity"|"timing"|"ncrType"|"sourceType"|"agency";
const ALL="All";
const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(v);
const unique=(key:FilterKey)=>[ALL,...Array.from(new Set(DEMO_INSPECTIONS.map(row=>row[key]))).sort()];

export default function ClientAnalyticsDemo(){
 const [project,setProject]=useState(ALL),[projectType,setProjectType]=useState(ALL),[country,setCountry]=useState(ALL),[commodity,setCommodity]=useState(ALL),[timing,setTiming]=useState(ALL),[ncr,setNcr]=useState(ALL),[ncrType,setNcrType]=useState(ALL),[sourceType,setSourceType]=useState(ALL),[agency,setAgency]=useState(ALL);
 const filtered=useMemo(()=>DEMO_INSPECTIONS.filter(row=>(project===ALL||row.project===project)&&(projectType===ALL||row.projectType===projectType)&&(country===ALL||row.country===country)&&(commodity===ALL||row.commodity===commodity)&&(timing===ALL||row.timing===timing)&&(ncr===ALL||(ncr==="With NCR"?row.ncr:!row.ncr))&&(ncrType===ALL||row.ncrType===ncrType)&&(sourceType===ALL||row.sourceType===sourceType)&&(agency===ALL||row.agency===agency)),[project,projectType,country,commodity,timing,ncr,ncrType,sourceType,agency]);
 const completed=filtered.filter(r=>r.status==="Completed"),totalSpend=filtered.reduce((s,r)=>s+r.spendUsd,0),onTime=completed.filter(r=>r.timing==="On time").length,projectsWithNcr=new Set(filtered.filter(r=>r.ncr).map(r=>r.project)).size;
 const bySource=group(filtered,r=>r.sourceType),byAgency=group(filtered,r=>r.agency),agencySpend=group(filtered.filter(r=>r.sourceType==="Agency"),r=>r.agency,r=>r.spendUsd),monthly=group(filtered,r=>r.date.slice(0,7),r=>r.spendUsd),geography=group(filtered,r=>r.country),byProjectType=group(filtered,r=>r.projectType),byCommodity=group(filtered,r=>r.commodity),byNcrType=group(filtered.filter(r=>r.ncr),r=>r.ncrType);
 const reset=()=>{setProject(ALL);setProjectType(ALL);setCountry(ALL);setCommodity(ALL);setTiming(ALL);setNcr(ALL);setNcrType(ALL);setSourceType(ALL);setAgency(ALL)};
 const download=()=>{const headers=["ID","Project","Project Type","Supplier","City","Country","Commodity","Inspection Type","Inspector","Source Type","Agency / Channel","Date","Status","Timing","Spend USD","NCR","NCR Type","Report ID"];const rows=filtered.map(r=>[r.id,r.project,r.projectType,r.supplier,r.city,r.country,r.commodity,r.inspectionType,r.inspector,r.sourceType,r.agency,r.date,r.status,r.timing,r.spendUsd,r.ncr?"Yes":"No",r.ncrType,r.reportId]);const csv=[headers,...rows].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="inspectsource-client-demo-inspections.csv";a.click();URL.revokeObjectURL(url)};
 return <main className="shell"><ClientWorkspaceSidebar demo/><section className="workspace">
  <section className="demoBanner" role="status"><strong>Client Demo · Synthetic data</strong><span>Deterministic analytics only. No production client records are read or written.</span></section>
  <header className="head"><div><p className="eyebrow">Client Analytics</p><h1>Inspection performance</h1><p>Cross-filter spend, timing, geography, project type, commodity and non-conformance performance — now including agency and independent sourcing provenance.</p></div><div className="actions"><button onClick={reset}>Reset filters</button><button className="download" onClick={download}>↓ Download data</button></div></header>
  <section className="filters" aria-label="Analytics slicers">
   <Filter label="Source Type" value={sourceType} values={unique("sourceType")} setValue={setSourceType}/><Filter label="Agency" value={agency} values={unique("agency")} setValue={setAgency}/><Filter label="Project" value={project} values={unique("project")} setValue={setProject}/><Filter label="Project Type" value={projectType} values={unique("projectType")} setValue={setProjectType}/><Filter label="Country" value={country} values={unique("country")} setValue={setCountry}/><Filter label="Commodity" value={commodity} values={unique("commodity")} setValue={setCommodity}/><Filter label="Timing" value={timing} values={unique("timing")} setValue={setTiming}/><Filter label="Non-conformance" value={ncr} values={[ALL,"With NCR","No NCR"]} setValue={setNcr}/><Filter label="NCR Type" value={ncrType} values={unique("ncrType")} setValue={setNcrType}/>
  </section>
  <section className="kpis" aria-label="Analytics KPIs"><Kpi label="Inspection spend" value={money(totalSpend)}/><Kpi label="Inspections in view" value={String(filtered.length)}/><Kpi label="On-time performance" value={`${(completed.length?onTime/completed.length*100:0).toFixed(1)}%`}/><Kpi label="Projects with NCRs" value={String(projectsWithNcr)}/><Kpi label="Agency-sourced" value={String(filtered.filter(r=>r.sourceType==="Agency").length)}/><Kpi label="Independent" value={String(filtered.filter(r=>r.sourceType==="Independent").length)}/></section>
  <section className="grid"><Panel title="Source type" subtitle="Agency vs independent inspection mix"><Bars rows={bySource} onSelect={setSourceType}/></Panel><Panel title="Agency / sourcing channel" subtitle="Inspection count by commercial sourcing channel"><Bars rows={byAgency} onSelect={setAgency}/></Panel><Panel title="Agency spend" subtitle="Synthetic spend attributed to agency channels"><Bars rows={agencySpend} onSelect={setAgency} moneyValues/></Panel><Panel title="Monthly spend trend" subtitle="Synthetic inspection spend by month"><Bars rows={monthly} moneyValues/></Panel><Panel title="Geography / map view" subtitle="Country activity in the current selection"><Bars rows={geography} onSelect={setCountry}/><span className="sr">Interactive geography map of synthetic inspection activity by country. Filter analytics to this country.</span></Panel><Panel title="Project type" subtitle="Inspection mix by project type"><Bars rows={byProjectType} onSelect={setProjectType}/></Panel><Panel title="Commodity" subtitle="Inspection mix by equipment / commodity"><Bars rows={byCommodity} onSelect={setCommodity}/></Panel><Panel title="NCR type" subtitle="Non-conformance mix in the current selection"><Bars rows={byNcrType} onSelect={setNcrType}/></Panel></section>
  <section className="panel records"><div className="recordHead"><div><p className="eyebrow">Inspection detail</p><h2>Cross-filtered inspection records</h2></div><span>{filtered.length} records</span></div><div className="tableWrap"><table><thead><tr><th>ID</th><th>Project</th><th>Source type</th><th>Agency / channel</th><th>Country</th><th>Commodity</th><th>Timing</th><th>Spend</th><th>NCR type</th><th>Status</th></tr></thead><tbody>{filtered.slice(0,30).map(r=><tr key={r.id}><td><strong>{r.id}</strong></td><td>{r.project}</td><td>{r.sourceType}</td><td>{r.agency}</td><td>{r.city}, {r.country}</td><td>{r.commodity}</td><td>{r.timing}</td><td>{money(r.spendUsd)}</td><td>{r.ncrType}</td><td>{r.status}</td></tr>)}</tbody></table></div></section>
  <section className="connectivity"><div><p className="eyebrow">Take the data with you</p><h2>API, Excel & Power BI connectivity</h2><p>Source attribution travels with the same normalized client dataset for governed integrations and reporting.</p></div><a href="/demo/client-data">Open Data & Integrations Demo →</a></section>
 </section><style jsx>{`.shell{max-width:1440px;margin:auto;padding:18px;display:grid;grid-template-columns:250px minmax(0,1fr);gap:20px}.workspace{min-width:0}.demoBanner,.head,.filters,.kpi,.panel,.connectivity{background:#fff;border:1px solid #dbe3ee;border-radius:14px}.demoBanner,.head,.connectivity{display:flex;justify-content:space-between;gap:14px;padding:14px}.demoBanner{background:#f0fdfa;color:#115e59}.head{margin-top:14px;padding:20px}.eyebrow{margin:0;font-size:.72rem;text-transform:uppercase;font-weight:900;color:#0f766e}.head h1,.panel h2,.connectivity h2{margin:3px 0 7px}.head p,.panel p,.connectivity p{color:#64748b}.actions{display:flex;gap:8px;align-items:flex-start}.actions button{padding:9px 12px;border:1px solid #cbd5e1;border-radius:8px;background:#fff;font-weight:800}.actions .download{background:#0f766e;color:#fff}.filters{margin:14px 0;padding:14px;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:9px}.filter{display:grid;gap:4px;font-size:.72rem;font-weight:800}.filter select{min-width:0;padding:8px;border:1px solid #cbd5e1;border-radius:7px}.kpis{display:grid;grid-template-columns:repeat(6,1fr);gap:9px;margin-bottom:14px}.kpi{padding:13px}.kpi strong{display:block;font-size:1.3rem}.kpi span{font-size:.72rem;color:#64748b}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.panel{padding:18px;min-width:0}.bars{display:grid;gap:7px}.barRow{display:grid;grid-template-columns:minmax(120px,190px) 1fr auto;gap:8px;align-items:center;border:0;background:transparent;text-align:left;width:100%;padding:3px}.clickable{cursor:pointer}.track{height:8px;background:#e2e8f0;border-radius:99px;overflow:hidden}.fill{display:block;height:100%;background:#0f766e}.records,.connectivity{margin-top:14px}.recordHead{display:flex;justify-content:space-between}.tableWrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:1100px;font-size:.8rem}th,td{text-align:left;padding:9px;border-top:1px solid #e2e8f0;white-space:nowrap}th{font-size:.68rem;text-transform:uppercase;color:#64748b}.sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}.connectivity a{font-weight:900;color:#0f766e}@media(max-width:1000px){.shell{grid-template-columns:1fr}.filters{grid-template-columns:repeat(3,1fr)}.kpis{grid-template-columns:repeat(3,1fr)}}@media(max-width:680px){.head,.demoBanner,.connectivity{display:grid}.filters,.kpis,.grid{grid-template-columns:1fr}}`}</style></main>
}
function Filter({label,value,values,setValue}:{label:string;value:string;values:string[];setValue:(v:string)=>void}){return <label className="filter">{label}<select value={value} onChange={e=>setValue(e.target.value)}>{values.map(v=><option key={v}>{v}</option>)}</select></label>}
function Kpi({label,value}:{label:string;value:string}){return <article className="kpi"><strong>{value}</strong><span>{label}</span></article>}
function Panel({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <article className="panel"><h2>{title}</h2><p>{subtitle}</p>{children}</article>}
function Bars({rows,onSelect,moneyValues=false}:{rows:{name:string;value:number}[];onSelect?:(v:string)=>void;moneyValues?:boolean}){if(!rows.length)return <p>No records in this selection.</p>;const max=Math.max(...rows.map(r=>r.value),1);return <div className="bars">{rows.slice(0,10).map(r=>{const c=<><span>{r.name}</span><span className="track"><span className="fill" style={{width:`${r.value/max*100}%`}}/></span><strong>{moneyValues?money(r.value):r.value}</strong></>;return onSelect?<button type="button" className="barRow clickable" key={r.name} onClick={()=>onSelect(r.name)}>{c}</button>:<div className="barRow" key={r.name}>{c}</div>})}</div>}
function group(rows:DemoInspection[],label:(r:DemoInspection)=>string,value:(r:DemoInspection)=>number=()=>1){const m=new Map<string,number>();rows.forEach(r=>m.set(label(r),(m.get(label(r))||0)+value(r)));return Array.from(m.entries()).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)}