"use client";

import Link from "next/link";
import { useState } from "react";

type Affiliation={agency:string;relationship:string;state:string;dates:string;resourceId:string;note:string};
const CURRENT:Affiliation[]=[
 {agency:"Northstar Inspection Partners",relationship:"Subcontractor",state:"Verified",dates:"Jan 15, 2025 – Dec 31, 2026",resourceId:"NS-R-1842",note:"Both agency and inspector confirmed. Independent sourcing is suppressed while this verified affiliation is active."},
 {agency:"Meridian Quality Services",relationship:"Affiliate",state:"Expiring",dates:"Mar 1, 2024 – Oct 31, 2026",resourceId:"MQ-V-771",note:"Verified affiliation nearing its agreed end date. Historical awards retain their original source attribution."}
];
const PENDING:Affiliation[]=[
 {agency:"Atlas Technical Inspection",relationship:"Employee",state:"Inspector Confirmation Pending",dates:"Proposed Sep 1, 2026 – Aug 31, 2027",resourceId:"ATI-E-2208",note:"Agency claim alone does not create a Verified affiliation and does not change independent marketplace eligibility."},
 {agency:"Harbor QA Group",relationship:"Subcontractor",state:"Disputed",dates:"Proposed Jul 1, 2026 – Dec 31, 2026",resourceId:"HQ-449",note:"Inspector disputed the relationship dates. No Verified affiliation exists while the dispute is unresolved."}
];
const HISTORY:Affiliation[]=[
 {agency:"Summit Vendor Assurance",relationship:"Employee",state:"Expired / Ended",dates:"Feb 1, 2022 – Dec 15, 2024",resourceId:"SVA-9014",note:"Ended affiliation remains auditable. Awards made through Summit remain attributed to Summit."}
];

function Cards({items}:{items:Affiliation[]}){return <div className="cards">{items.map(a=><article key={a.agency}><div className="head"><div><strong>{a.agency}</strong><small>{a.relationship} · {a.resourceId}</small></div><span className="state">{a.state}</span></div><dl><dt>Relationship dates</dt><dd>{a.dates}</dd><dt>Matching identity</dt><dd>InspectSource Inspector ID IS-20418 + non-government contact data</dd></dl><p>{a.note}</p></article>)}</div>}

export default function InspectorAffiliationCenter(){
 const [tab,setTab]=useState<"current"|"pending"|"history">("current");
 const [notice,setNotice]=useState("");
 return <main className="shell"><section className="banner"><b>Inspector Demo · Synthetic data</b><span>No production affiliation, PII, notification, eligibility or authorization changes occur here.</span></section><header><div><p className="eyebrow">InspectorHub · Affiliation Center</p><h1>Your agency relationships</h1><p>One permanent InspectSource inspector identity can have separate, auditable relationships with multiple inspection agencies.</p></div><Link href="/demo/inspector">← Inspector Demo</Link></header>
 <section className="rule"><h2>Dual confirmation protects both sides</h2><p>An agency can claim a relationship, but it becomes <b>Verified only after positive inspector confirmation</b>. If the inspector proposes different relationship type or dates, the agency must reconfirm. Either side may end a relationship without rewriting historical award/source attribution.</p><p><b>Marketplace rule preview:</b> any active Verified agency affiliation suppresses the Independent sourcing channel. Pending, disputed and unverified claims do not.</p></section>
 {notice&&<div role="status" className="notice">{notice}</div>}
 <nav className="tabs" aria-label="Affiliation record views">{[["current","Current / Verified"],["pending","Pending / Disputed"],["history","Historical"]].map(([v,l])=><button key={v} aria-pressed={tab===v} onClick={()=>setTab(v as typeof tab)}>{l}</button>)}</nav>
 <section className="panel"><div className="title"><div><p className="eyebrow">{tab==="current"?"Active relationships":tab==="pending"?"Needs attention":"Audit history"}</p><h2>{tab==="current"?"Current affiliations":tab==="pending"?"Claims and disputes":"Ended affiliations"}</h2></div><span>Permanent Inspector ID · IS-20418</span></div>{tab==="current"&&<Cards items={CURRENT}/>} {tab==="pending"&&<><Cards items={PENDING}/><div className="actions"><button onClick={()=>setNotice("Confirmation previewed — demo only; no affiliation was changed.")}>Confirm selected claim</button><button onClick={()=>setNotice("Correction proposal previewed — agency reconfirmation would be required.")}>Propose correction</button><button onClick={()=>setNotice("Dispute previewed — demo only; no notification was sent.")}>Dispute claim</button></div></>} {tab==="history"&&<Cards items={HISTORY}/>}</section>
 <section className="safety"><h2>Identity and audit boundary</h2><p>Matching uses name plus email/phone/country, the agency's own internal employee/vendor/resource ID, and InspectSource's permanent Inspector ID after registration. <b>SSN, passport number, national ID and similar government identifiers are not used for affiliation matching.</b></p><p>Begin/end dates are visible to the agency. Ending or correcting a relationship does not silently rewrite inspection awards, opportunity source, commercial channel or historical attribution.</p></section>
 <style jsx>{`.shell{max-width:1180px;margin:auto;padding:18px}.banner,.rule,.panel,.safety{border:1px solid #dbe3ee;border-radius:14px;background:#fff}.banner{padding:10px 14px;background:#f0fdfa;color:#115e59;display:flex;justify-content:space-between;gap:12px}header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;padding:20px 2px 12px}header h1,.panel h2,.rule h2,.safety h2{margin:4px 0 8px}header p,.rule p,.safety p,.cards p{color:#64748b}.eyebrow{margin:0;text-transform:uppercase;letter-spacing:.11em;font-size:.72rem;font-weight:900;color:#0f766e}.rule,.safety,.panel{padding:18px;margin-bottom:14px}.tabs{display:flex;gap:8px;margin:0 0 12px;flex-wrap:wrap}.tabs button,.actions button{border:1px solid #cbd5e1;border-radius:9px;background:#fff;padding:9px 12px;font-weight:800;cursor:pointer}.tabs button[aria-pressed="true"]{background:#0f172a;color:#fff}.notice{padding:10px 12px;margin-bottom:12px;border-radius:10px;background:#ecfdf5;color:#166534}.title,.head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.title>span{font-size:.82rem;color:#475569}.cards{display:grid;gap:10px}.cards article{border:1px solid #e2e8f0;border-radius:12px;padding:14px;background:#f8fafc}.head small{display:block;color:#64748b;margin-top:4px}.state{font-size:.76rem;font-weight:900;padding:5px 8px;border-radius:999px;background:#e0f2fe;color:#075985}.cards dl{display:grid;grid-template-columns:150px 1fr;gap:5px 10px;font-size:.82rem}.cards dd{margin:0}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.safety{background:#fffbeb;border-color:#fde68a}@media(max-width:650px){.banner,header,.title,.head{display:grid}.cards dl{grid-template-columns:1fr}.cards dt{font-weight:800}.cards dd{margin-bottom:6px}}`}</style></main>;
}