"use client";
import Link from "next/link";

const audiences = [
  { key:"client", label:"For Clients", title:"Source and manage inspection resources.", copy:"Use contracted agencies, independent inspectors, or both; coordinate active inspections and keep history, contracts and intelligence together.", features:["Natural language, email, or structured requests","Contracted-agency and independent sourcing","Inspection workflow, history, analytics and payments"], primary:["Find Inspectors","/find-inspectors"], secondary:["Explore Client Workspace →","/client-dashboard"], demo:["Client Demo","Explore the client workflow with synthetic inspection data.","/demo/client"] },
  { key:"agency", label:"For Agencies", title:"Deploy capacity and grow your inspection network.", copy:"Manage employees, subcontractors and affiliates, respond to client opportunities, deliver inspections and recruit marketplace inspectors when capacity is tight.", features:["Resource pool, affiliations and capacity","Opportunities, reports, NCRs and contracts","Commercial, utilization and geographic analytics"], primary:["Explore Agency Workspace","/demo/agency"], secondary:["Find Inspectors / Recruiting →","/demo/agency#find-inspectors-recruiting"], demo:["Agency Demo","See agency operations populated with synthetic resources and contracts.","/demo/agency"] },
  { key:"inspector", label:"For Inspectors", title:"Build your profile and run inspection work.", copy:"Show qualifications, manage availability and opportunities, complete reports, track affiliations and keep professional activity organized.", features:["Qualifications and professional profile","Opportunities, schedule and assignments","Reports, history and selection insights"], primary:["Explore InspectorHub","/inspectorhub"], secondary:["Join as an Inspector →","/register"], demo:["Inspector Demo","See InspectorHub populated with synthetic work history and activity.","/demo/inspector"] },
] as const;

export default function HomePage(){return <div className="homeShell">
<section className="brandBanner" aria-labelledby="home-brand-line"><p>Global vendor inspection marketplace</p><h1 id="home-brand-line">InspectSource — Eyes, Ears, and Expertise, Everywhere.</h1><span>One marketplace for clients, inspection agencies, and inspectors. One identity can support the roles you are authorized to use.</span></section>
<section className="audienceGrid" aria-label="InspectSource experiences">{audiences.map(a=><article className={`audienceCard ${a.key}Card`} key={a.key}><div className="cardLabel">{a.label}</div><h2>{a.title}</h2><p>{a.copy}</p><div className="featureList">{a.features.map(f=><span key={f}>{f}</span>)}</div><div className="actions"><Link className="button" href={a.primary[1]}>{a.primary[0]}</Link><Link className="textLink" href={a.secondary[1]}>{a.secondary[0]}</Link></div><div className="demoEntry"><div><strong>{a.demo[0]}</strong><span>{a.demo[1]}</span></div><Link href={a.demo[2]}>Open Demo →</Link></div></article>)}</section>
<section className="trustStrip"><strong>One InspectSource sign-in.</strong><span>Demo experiences use synthetic records; authenticated workspaces use account permissions and live data.</span><Link href="/login">Log in →</Link></section>
<style jsx>{`.homeShell{display:grid;gap:16px;padding:6px 0 36px}.brandBanner{position:relative;overflow:hidden;padding:28px 34px;border-radius:20px;background:linear-gradient(120deg,#0f172a 0%,#12375a 58%,#0f766e 120%);color:#fff}.brandBanner p{margin:0 0 6px;font-size:.76rem;font-weight:900;letter-spacing:.16em;text-transform:uppercase;color:#a7f3d0}.brandBanner h1{max-width:900px;margin:0;font-size:clamp(2rem,4vw,3.4rem);line-height:1.02;letter-spacing:-.04em}.brandBanner span{display:block;max-width:820px;margin-top:12px;color:#dbeafe;line-height:1.5}.audienceGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.audienceCard{display:flex;flex-direction:column;min-height:420px;padding:22px;border:1px solid #dbe3ec;border-radius:18px;background:#fff;box-shadow:0 8px 24px rgba(15,23,42,.05)}.clientCard{border-top:5px solid #2563eb;background:linear-gradient(180deg,#eff6ff 0,#fff 30%)}.agencyCard{border-top:5px solid #7c3aed;background:linear-gradient(180deg,#f5f3ff 0,#fff 30%)}.inspectorCard{border-top:5px solid #0f766e;background:linear-gradient(180deg,#ecfdf5 0,#fff 30%)}.cardLabel{width:max-content;padding:5px 8px;border-radius:999px;background:rgba(255,255,255,.85);font-size:.7rem;font-weight:900;letter-spacing:.12em;text-transform:uppercase;color:#475569}.audienceCard h2{margin:13px 0 8px;font-size:clamp(1.35rem,2vw,1.8rem);line-height:1.1;color:#0f172a}.audienceCard p{margin:0;color:#526074;line-height:1.5}.featureList{display:grid;gap:7px;margin:16px 0}.featureList span{position:relative;padding-left:20px;color:#334155;font-size:.9rem;font-weight:650}.featureList span:before{content:"✓";position:absolute;left:0;font-weight:900;color:#0f766e}.actions{display:grid;gap:9px;margin-top:auto;padding-top:10px}.button{display:inline-flex;justify-content:center;padding:10px 12px;border-radius:9px;text-decoration:none;font-weight:850;color:#fff;background:#0f172a}.textLink{font-size:.88rem;font-weight:750;text-decoration:none;color:#334155}.demoEntry{display:grid;gap:8px;margin-top:14px;padding:12px;border-radius:12px;background:#f8fafc;border:1px solid #dbe3ec}.demoEntry div{display:grid;gap:2px}.demoEntry strong{color:#0f172a}.demoEntry span{font-size:.78rem;line-height:1.3;color:#64748b}.demoEntry :global(a){text-decoration:none;font-size:.82rem;font-weight:850;color:#0f172a}.trustStrip{display:flex;align-items:center;justify-content:center;gap:9px;flex-wrap:wrap;padding:12px 16px;border:1px solid #e2e8f0;border-radius:13px;background:#f8fafc;color:#475569;font-size:.88rem}.trustStrip strong{color:#0f172a}.trustStrip :global(a){font-weight:850;color:#1d4ed8;text-decoration:none}@media(max-width:1050px){.audienceGrid{grid-template-columns:1fr}.audienceCard{min-height:0}.brandBanner{padding:25px 22px}}`}</style></div>}
