export type InspectorProfile = {
  id: string;
  user_id: string;
  name: string;
  headline: string;
  company: string;
  email: string;
  phone: string;
  office_address: string;
  office_lat: number | null;
  office_lng: number | null;
  base_city: string;
  base_state: string;
  base_country: string;
  travel_distance: number | null;
  distance_unit: "miles" | "kilometers";
  mileage_rate: number | null;
  kilometer_rate: number | null;
  certifications: string[];
  methods: string[];
  industries: string[];
  hourly_rate: number | null;
  day_rate: number | null;
  bio: string;
  available: boolean;
  years_experience: number | null;
  primary_discipline: string;
  willing_to_travel: boolean;
  remote_review_available: boolean;
  created_at: string;
  updated_at: string;
};
