"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import ClientWorkspaceSidebar from "@/components/ClientWorkspaceSidebar";
import { DEMO_INSPECTIONS, DEMO_COMPLETED, DEMO_NCR_RATE, type DemoInspection } from "@/lib/clientDemoInspections";

const reportHref=(row:DemoInspection)=>`/api/demo/report?id=${encodeURIComponent(row.reportId)}&project=${encodeURIComponent(row.project)}&supplier=${encodeURIComponent(row.supplier)}&location=${encodeURIComponent(`${row.city}, ${row.country}`)}&date=${encodeURIComponent(row.date)}&commodity=${encodeURIComponent(row.commodity)}&inspection=${encodeURIComponent(row.inspectionType)}&inspector=${encodeURIComponent(row.inspector)}&ncr=${row.ncr?"1":"0"}`;

export default function ClientHistoryDemo(){
 const [project,setProject]=useState("All projects"),[expanded,setExpanded]=useState<string|null>(null),[showApiHighlight,setShowApiHighlight]=useState(true);
 const projects=Array.from(new Set(DEMO_INSPECTIONS.map(x=>x.project)));
 const filtered=useMemo(()=>DEMO_INSPECTIONS.filter(x=>project==="All projects"||x.project===project),[project]);
 const completed=filtered.filter(x=>x.status==="Completed"),active=filtered.filter(x=>x.status==="In Progress"),pending=filtered.filter(x=>x.status==="Pending");
 return <main className="shell"><ClientWorkspaceSidebar demo/><section className="workspace">
  <section className="demoBanner"><strong>Client Demo · Synthetic data</strong><span>Global inspection activity across three fictional capital projects.</span></section>
  <header className="head"><div><p className="eyebrow">Inspection History</p><h1>Global inspection portfolio</h1><p>Completed, active and pending inspection activity across upstream, downstream and offshore wind supply chains.</p></div><label>Project<select value={project} onChange={e=>setProject(e.target.value)}><option>All projects</option>{projects.map(p=><option key={p}>{p}</option>)}</select></label></header>
  <section className="kpis"><Kpi label="Completed inspections" value={String(DEMO_COMPLETED.length)}/><Kpi label="Projects" value="3"/><Kpi label="Countries represented" value={String(new Set(DEMO_INSPECTIONS.map(x=>x.country)).size)}/><Kpi label="NCR rate" value={`${DEMO_NCR_RATE.toFixed(1)}%`} note="vs. 2.1% global running average"/></section>
  <section className="projectCards">{projects.map(p=>{const rows=DEMO_INSPECTIONS.filter(x=>x.project===p);return <button key={p} onClick={()=>setProject(p)}><span>{rows[0]?.projectType}</span><strong>{p}</strong><b>{rows.length} inspections</b></button>})}</section>
  <div className={`historyLayout${showApiHighlight?"":" historyLayoutSingle"}`}>
   <div>
    <Group title="Active Inspections" rows={active} expanded={expanded} setExpanded={setExpanded}/>
    <Group title="Pending Requests" rows={pending} expanded={expanded} setExpanded={setExpanded}/>
    <Group title="Completed Inspections & Submitted Reports" rows={completed} expanded={expanded} setExpanded={setExpanded}/>
   </div>
   {showApiHighlight&&<aside className="apiHighlight" aria-label="Inspection History API"><button type="button" className="dismiss" aria-label="Dismiss Inspection History API highlight" onClick={()=>setShowApiHighlight(false)}>×</button><p className="eyebrow">Data access</p><h2>Inspection History API</h2><p>Connect inspection history, reports and portfolio data to your own systems without re-keying records.</p><ul><li>API-ready inspection history</li><li>Excel and CSV export paths</li><li>Power BI and enterprise integration demo</li></ul><Link href="/demo/client-data">Explore data connectivity →</Link><small>Synthetic demo only. No credentials or production data are exposed.</small></aside>}
  </div>
 </section><style jsx>{`.shell{max-width:1440px;margin:auto;padding:18px 18px 70px;display:grid;grid-template-columns:250px minmax(0,1fr);gap:20px}.workspace{min-width:0}.demoBanner,.head,.kpi,.projectCards button{background:#fff;border:1px solid #dbe3ee}.demoBanner{display:flex;justify-content:space-between;gap:12px;padding:10px 14px;border-radius:12px;background:#f0fdfa;color:#115e59}.head{margin-top:14px;border-radius:16px;padding:24px;display:flex;justify-content:space-between;gap:24px}.head h1{margin:3px 0 8px}.head p{color:#64748b;max-width:850px}.head label{display:grid;gap:6px;font-size:.78rem;font-weight:800;min-width:220px}.head select{padding:10px;border:1px solid #cbd5e1;border-radius:9px;background:#fff}.eyebrow{margin:0;font-size:.72rem;letter-spacing:.12em;text-transform:uppercase;font-weight:900;color:#0f766e}.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.kpi{padding:15px;border-radius:12px}.kpi strong{display:block;font-size:1.45rem}.kpi span,.kpi small{display:block;color:#64748b;font-size:.76rem}.projectCards{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:14px}.projectCards button{padding:15px;border-radius:12px;display:grid;gap:5px;text-align:left;cursor:pointer}.projectCards button:hover{border-color:#0f766e;background:#f0fdfa}.projectCards span{color:#64748b;font-size:.75rem}.projectCards b{color:#0f766e;font-size:.78rem}.historyLayout{display:grid;grid-template-columns:minmax(0,1fr) 310px;gap:14px;align-items:start}.historyLayoutSingle{grid-template-columns:minmax(0,1fr)}.apiHighlight{position:sticky;top:18px;background:linear-gradient(155deg,#eff6ff,#f0fdfa);border:1px solid #bfdbfe;border-radius:16px;padding:18px;box-shadow:0 10px 30px rgba(15,23,42,.08)}.apiHighlight h2{margin:5px 28px 8px 0;font-size:1.12rem}.apiHighlight p,.apiHighlight li,.apiHighlight small{color:#475569;line-height:1.5}.apiHighlight ul{padding-left:18px;margin:12px 0}.apiHighlight a{display:inline-block;text-decoration:none;font-weight:900;color:#1d4ed8;margin:4px 0 12px}.apiHighlight small{display:block;font-size:.73rem}.dismiss{position:absolute;top:10px;right:10px;border:0;background:transparent;color:#64748b;font-size:1.35rem;line-height:1;cursor:pointer;border-radius:7px;min-width:32px;min-height:32px}.dismiss:hover,.dismiss:focus-visible{background:#fff;color:#0f172a}@media(max-width:1180px){.historyLayout{grid-template-columns:minmax(0,1fr) 260px}}@media(max-width:980px){.shell{grid-template-columns:1fr}.kpis,.projectCards{grid-template-columns:1fr 1fr}.historyLayout{grid-template-columns:1fr}.apiHighlight{position:static}}@media(max-width:620px){.demoBanner,.head{display:grid}.kpis,.projectCards{grid-template-columns:1fr}}`}</style></main>
}
function Group({title,rows,expanded,setExpanded}:{title:string;rows:DemoInspection[];expanded:string|null;setExpanded:(x:string|null)=>void}){return <section className="group"><div className="groupHead"><div><h2>{title}</h2><span>{rows.length} record{rows.length===1?"":"s"}</span></div></div><div className="tableHeader"><span>ID / Project</span><span>Supplier / Commodity</span><span>Location</span><span>Inspection</span><span>Date</span><span></span></div>{rows.map(row=>{const open=expanded===row.id;return <article className="row" key={row.id}><button className="rowSummary" aria-expanded={open} onClick={()=>setExpanded(open?null:row.id)}><div><strong>{row.id}</strong><small>{row.project}</small></div><div><strong>{row.supplier}</strong><small>{row.commodity}</small></div><span>{row.city}, {row.country}</span><span>{row.inspectionType}</span><span>{row.date}</span><b>{open?"−":"+"}</b></button>{open&&<div className="rowDetails"><Detail label="Inspector" value={row.inspector}/><Detail label="Status" value={row.status}/><Detail label="NCR" value={row.ncr?row.ncrType:"None"}/><Detail label="Report" value={row.reportId}/>{row.status==="Completed"&&<a className="reportButton" href={reportHref(row)} target="_blank" rel="noreferrer">Open report PDF →</a>}</div>}</article>})}<style jsx>{`.group{background:#fff;border:1px solid #dbe3ee;border-radius:16px;margin:14px 0;overflow:hidden}.group:first-child{margin-top:0}.groupHead{padding:16px 18px;background:#f8fafc;border-bottom:1px solid #e2e8f0}.groupHead h2{margin:0;font-size:1.12rem}.groupHead span{color:#64748b;font-size:.8rem}.tableHeader,.rowSummary{display:grid;grid-template-columns:1.25fr 1.35fr 1fr 1fr .8fr 28px;gap:12px;align-items:center}.tableHeader{padding:10px 18px;background:#fff;color:#64748b;font-size:.69rem;text-transform:uppercase;font-weight:900}.row{border-top:1px solid #e2e8f0}.rowSummary{width:100%;border:0;background:#fff;color:#0f172a;text-align:left;padding:14px 18px;cursor:pointer}.rowSummary:hover{background:#f8fafc}.rowSummary div{display:grid;gap:2px}.rowSummary small{color:#64748b}.rowSummary>span{color:#334155}.rowDetails{padding:14px 18px;background:#f8fafc;display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.reportButton{grid-column:1/-1;width:max-content;text-decoration:none;background:#0f766e;color:#fff;border-radius:8px;padding:9px 12px;font-weight:800}@media(max-width:900px){.tableHeader{display:none}.rowSummary{grid-template-columns:1fr 1fr}.rowDetails{grid-template-columns:1fr 1fr}}@media(max-width:620px){.rowSummary,.rowDetails{grid-template-columns:1fr}}`}</style></section>}
function Kpi({label,value,note}:{label:string;value:string;note?:string}){return <article className="kpi"><strong>{value}</strong><span>{label}</span>{note&&<small>{note}</small>}</article>}
function Detail({label,value}:{label:string;value:string}){return <div><span style={{display:"block",color:"#64748b",fontSize:'.72rem'}}>{label}</span><strong>{value}</strong></div>}
