import Link from "next/link";

const affiliations = [
  {id:"IS-20418",name:"Maya Chen",type:"Employee",state:"Verified",dates:"Jan 1, 2025 — Dec 31, 2027",agencyId:"EMP-4812",action:"Active — dual confirmed",note:"Inspector confirmed Jan 3, 2025 • Agency reconfirmed Jan 3, 2025"},
  {id:"IS-11742",name:"Omar Haddad",type:"Subcontractor",state:"Expiring",dates:"Mar 1, 2026 — Oct 15, 2026",agencyId:"VEN-2291",action:"Renewal review",note:"Existing awards retain Northstar source attribution after end date."},
  {id:"IS-28106",name:"Daniel Okafor",type:"Subcontractor",state:"Inspector Confirmation Pending",dates:"Proposed Sep 20, 2026 — Sep 19, 2027",agencyId:"VEN-3188",action:"Await inspector",note:"Pending claim does not suppress Daniel's independent marketplace eligibility."},
  {id:"IS-44127",name:"Priya Nair",type:"Affiliate",state:"Disputed",dates:"Proposed Aug 1, 2026 — Jul 31, 2027",agencyId:"AFF-0921",action:"Resolve dispute",note:"Commercial routing is held; no Verified affiliation exists."},
  {id:"IS-33091",name:"Elena Rossi",type:"Affiliate",state:"Expired / Ended",dates:"Feb 1, 2024 — Aug 31, 2026",agencyId:"AFF-0447",action:"Historical",note:"End date is immutable history for prior awards; independent eligibility may resume if opted in."},
];

export default function AgencyAffiliationsDemo(){return <main className="wrap">
  <div className="notice"><strong>Demo Mode</strong> — synthetic affiliation records only. No production identity, notification, authorization or matching changes occur here.</div>
  <header><div><span className="eyebrow">Agency Workspace / Resource Pool</span><h1>Resource Affiliations</h1><p>Claim and manage agency relationships without changing the inspector's permanent InspectSource identity.</p></div><Link href="/demo/agency">← Agency Workspace</Link></header>
  <section className="kpis"><article><b>126</b><span>Total resources</span></article><article><b>108</b><span>Verified</span></article><article><b>7</b><span>Confirmation pending</span></article><article><b>6</b><span>Expiring</span></article><article><b>2</b><span>Disputed</span></article></section>
  <section className="card"><div className="head"><div><h2>Affiliation lifecycle</h2><p>Neither agency claim nor inspector response alone creates Verified status. Corrections to relationship type or dates require the other party to reconfirm.</p></div><button type="button">+ Claim / add inspector</button></div>
    <div className="flow"><span>Agency Claimed</span><i>→</i><span>Inspector Confirmation Pending</span><i>→</i><span>Verified</span><i>→</i><span>Expiring</span><i>→</i><span>Expired / Ended</span><em>Disputed can branch from any unverified change</em></div>
  </section>
  <section className="card"><h2>Agency Resource Affiliations</h2><div className="filters" aria-label="Affiliation status filters"><button>All</button><button>Pending</button><button>Verified</button><button>Expiring</button><button>Disputed</button><button>Ended</button></div>
    <div className="table"><table><thead><tr><th>Inspector identity</th><th>Relationship</th><th>Status</th><th>Begin / end</th><th>Agency resource ID</th><th>Next action</th></tr></thead><tbody>{affiliations.map(a=><tr key={a.id}><td><b>{a.name}</b><small>{a.id} • permanent InspectSource ID</small></td><td>{a.type}</td><td><span className="pill">{a.state}</span></td><td>{a.dates}</td><td>{a.agencyId}</td><td><b>{a.action}</b><small>{a.note}</small></td></tr>)}</tbody></table></div>
  </section>
  <div className="grid"><section className="card"><h2>Claim / match policy</h2><p>Use non-government matching information: name, email or phone, country, agency internal employee/vendor/resource ID, then the permanent InspectSource Inspector ID after match or registration.</p><strong>Never use SSN, passport number, national ID or similar government identifiers.</strong></section>
  <section className="card"><h2>Audit & sourcing safeguards</h2><ul><li>Both agency and inspector can end an affiliation.</li><li>Historical dates and awarded-work source attribution are preserved.</li><li>Upload order never creates commercial ownership.</li><li>Only active Verified affiliations suppress the Independent sourcing channel.</li><li>Pending, disputed and other unverified claims do not suppress Independent eligibility.</li></ul></section></div>
  <p className="fine">Production persistence, notifications, PII processing, authorization, sourcing enforcement and material matching rules remain review-gated. This page intentionally performs no writes.</p>
  <style>{`*{box-sizing:border-box}.wrap{max-width:1400px;margin:0 auto;padding:20px;color:#0f172a}.notice{padding:10px 14px;background:#eff6ff;border:1px solid #bfdbfe;border-radius:10px;color:#1e40af;margin-bottom:16px}header,.head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}header h1{margin:5px 0;font-size:2rem}header p,.card p,.card li{color:#475569}header a{color:#1d4ed8;font-weight:700}.eyebrow{text-transform:uppercase;letter-spacing:.08em;font-size:.72rem;font-weight:800;color:#2563eb}.kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:18px 0}.kpis article,.card{border:1px solid #e2e8f0;border-radius:14px;background:white;padding:16px}.kpis b{display:block;font-size:1.5rem}.kpis span{color:#64748b}.card{margin-bottom:14px}.card h2{margin-top:0}.head button,.filters button{border:0;border-radius:9px;background:#1d4ed8;color:white;padding:10px 14px;font-weight:700}.flow{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.flow span,.pill{background:#f1f5f9;border-radius:999px;padding:6px 10px;font-size:.78rem;font-weight:700}.flow em{width:100%;color:#92400e;font-size:.78rem}.filters{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0}.filters button{background:#f1f5f9;color:#334155;padding:7px 10px}.filters button:first-child{background:#dbeafe;color:#1d4ed8}.table{overflow:auto}table{width:100%;border-collapse:collapse;font-size:.82rem}th,td{text-align:left;padding:11px;border-top:1px solid #e2e8f0;vertical-align:top}th{color:#64748b}td small{display:block;color:#64748b;margin-top:4px;max-width:300px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.fine{font-size:.78rem;color:#64748b}@media(max-width:850px){.kpis{grid-template-columns:1fr 1fr}.grid{grid-template-columns:1fr}header,.head{display:block}.head button{margin-bottom:10px}}`}</style>
</main>}
