"use client";

import { useEffect, useMemo, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase";

type Asset={id:string;asset_code:string;name:string;asset_type:string|null;manufacturer:string|null;criticality:string;metadata:any};
type Risk={id:string;severity:string;title:string;supplier_name:string|null;schedule_impact:string|null;status:string};
type Action={id:string;priority:string;recommendation:string;rationale:string|null;status:string};

export default function DemoShowcase(){
 const supabase=useMemo(()=>supabaseBrowser(),[]);const [assets,setAssets]=useState<Asset[]>([]);const [risks,setRisks]=useState<Risk[]>([]);const [actions,setActions]=useState<Action[]>([]);const [msg,setMsg]=useState("Loading synthetic industrial project...");
 useEffect(()=>{void initialize()},[]);
 async function initialize(){const {data:a}=await supabase.auth.getUser();if(!a.user){setMsg("Log in to load the synthetic demo environment.");return;} const {error}=await supabase.rpc("load_demo_environment");if(error){setMsg(error.message);return;}await load();setMsg("")}
 async function load(){const [ar,rr,cr]=await Promise.all([supabase.from("assets").select("id,asset_code,name,asset_type,manufacturer,criticality,metadata").contains("metadata",{demo:"gulf-coast-expansion"}).order("asset_code"),supabase.from("inspection_risk_signals").select("id,severity,title,supplier_name,schedule_impact,status").order("detected_at",{ascending:false}),supabase.from("coordinator_actions").select("id,priority,recommendation,rationale,status").eq("status","proposed").order("created_at",{ascending:false})]);setAssets((ar.data||[]) as Asset[]);setRisks((rr.data||[]).slice(0,8) as Risk[]);setActions((cr.data||[]).slice(0,8) as Action[])}
 const project=assets.find(a=>a.asset_code==="GCRE-2027");const equipment=assets.filter(a=>a.asset_code!=="GCRE-2027");const attention=equipment.filter(a=>["attention","late"].includes(a.metadata?.status));
 return <main className="page"><section className="hero"><p className="eyebrow">Synthetic demonstration environment</p><h1>Gulf Coast Refinery Expansion</h1><p>A fictional $420M refinery expansion showing how InspectSource can continuously focus inspection resources on quality, supplier performance and critical-path risk.</p></section>{msg&&<p className="notice">{msg}</p>}{project&&<><section className="stats"><Stat n="68%" l="Project fabrication progress"/><Stat n={String(equipment.length)} l="Tracked assets/packages"/><Stat n={String(attention.length)} l="Assets needing attention"/><Stat n={String(risks.filter(r=>r.severity==="high"||r.severity==="critical").length)} l="High/critical risk signals"/></section><section className="card"><h2>Asset portfolio</h2><div className="table">{equipment.map(a=><article key={a.id}><div><strong>{a.asset_code}</strong><span>{a.name}</span></div><span>{a.manufacturer||"—"}</span><span>{a.metadata?.progress||0}% complete</span><b className={a.metadata?.status}>{String(a.metadata?.status||"active").replaceAll("_"," ")}</b></article>)}</div></section><div className="cols"><section className="card"><h2>What the system is seeing</h2>{risks.map(r=><article className="item" key={r.id}><b>{r.severity.toUpperCase()}</b><div><strong>{r.title}</strong><p>{r.supplier_name}</p><small>{r.schedule_impact}</small></div></article>)}</section><section className="card"><h2>Coordinator feedback loop</h2>{actions.map(a=><article className="item" key={a.id}><b>{a.priority.toUpperCase()}</b><div><strong>{a.recommendation}</strong><p>{a.rationale}</p></div></article>)}</section></div><section className="story"><h2>Demo story</h2><p><strong>Lone Star Process Equipment</strong> has repeated material-traceability and alloy-control failures on critical-path piping. InspectSource therefore proposes increasing surveillance to three visits per week and adding daily hydrotest readiness checks on PV-101.</p><p>At the same time, <strong>Gulf Thermal Systems</strong> has four clean surveillance visits and strong documentation performance, so the coordinator can reduce routine coverage there and reallocate inspection hours to the weak supplier.</p><p>This is the recursive loop: <strong>inspect → capture evidence → identify risk → change the inspection plan → inspect again.</strong></p></section></>}
 <style jsx>{`.page{max-width:1160px;margin:auto;padding:30px 18px 80px}.hero,.card,.story,.stat{background:#fff;border:1px solid #e2e8f0;border-radius:18px}.hero{padding:30px}.eyebrow{font-size:.75rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.hero h1{margin:4px 0;font-size:2rem}.hero p,.item p,small{color:#64748b}.notice{padding:14px;background:#f1f5f9;border-radius:10px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:16px 0}.stat{padding:18px}.stat strong{font-size:1.8rem;display:block}.stat span{color:#64748b}.card,.story{padding:22px;margin-bottom:16px}.table article{display:grid;grid-template-columns:2fr 2fr 1fr 1fr;gap:12px;padding:13px 0;border-top:1px solid #e2e8f0}.table article div{display:grid}.table article div span{color:#64748b}.table b{text-transform:capitalize}.late,.attention{color:#b45309}.on_track,.recovering{color:#166534}.cols{display:grid;grid-template-columns:1fr 1fr;gap:16px}.item{display:grid;grid-template-columns:auto 1fr;gap:12px;padding:14px 0;border-top:1px solid #e2e8f0}.item p{margin:4px 0}.story p{line-height:1.65}@media(max-width:760px){.stats,.cols{grid-template-columns:1fr 1fr}.table article{grid-template-columns:1fr}.hero h1{font-size:1.6rem}}@media(max-width:480px){.stats,.cols{grid-template-columns:1fr}}`}</style></main>}
function Stat({n,l}:{n:string;l:string}){return <div className="stat"><strong>{n}</strong><span>{l}</span></div>}
