create table if not exists public.equipment_families (
 id uuid primary key default gen_random_uuid(), family_code text not null unique, name text not null,
 discipline text not null, description text, common_inspection_activities text[] not null default '{}',
 common_finding_categories text[] not null default '{}', common_test_milestones text[] not null default '{}',
 common_document_requirements text[] not null default '{}', created_at timestamptz not null default now()
);

insert into public.equipment_families(family_code,name,discipline,common_inspection_activities,common_finding_categories,common_test_milestones,common_document_requirements) values
('TRANSFORMER','Power Transformer','Electrical',array['Document review','Material identification / traceability','Visual inspection','Dimensional inspection','Electrical inspection / testing','Final inspection','Release inspection'],array['Documentation','Nameplate / identification','Workmanship','Wiring / terminations','Insulation / dielectric','Oil / fluid','Accessories','Test result'],array['Design/document review','In-process surveillance','Factory acceptance test','Final inspection','Shipment release'],array['Approved drawings','Data sheets','Test procedures','Calibration records','Routine/type test reports','Packing list']),
('SWITCHGEAR','Switchgear','Electrical',array['Document review','Visual inspection','Dimensional inspection','Electrical inspection / testing','Functional testing','Final inspection'],array['Documentation','Wiring / terminations','Breaker / device configuration','Busbar','Interlocks','Protection / controls','Workmanship','Test result'],array['Design/document review','In-process surveillance','Factory acceptance test','Final inspection','Shipment release'],array['Approved drawings','Single-line diagrams','Schematics','FAT procedure','Calibration records','Test reports']),
('GENERATOR','Generator Set','Mechanical / Electrical',array['Document review','Visual inspection','Dimensional inspection','Functional testing','Electrical inspection / testing','Final inspection'],array['Documentation','Engine / mechanical','Generator electrical','Controls','Fuel system','Cooling system','Workmanship','Test result'],array['In-process surveillance','Load test / FAT','Functional test','Final inspection','Shipment release'],array['Approved drawings','Data sheets','Test procedures','Load test report','Certificates','Packing list']),
('UPS','UPS System','Electrical',array['Document review','Visual inspection','Electrical inspection / testing','Functional testing','Final inspection'],array['Documentation','Wiring / terminations','Controls / firmware','Battery interface','Bypass / transfer','Workmanship','Test result'],array['Factory acceptance test','Functional test','Final inspection','Shipment release'],array['Approved drawings','Schematics','FAT procedure','Test reports','Software / settings record']),
('BATTERY','Battery / Energy Storage','Electrical',array['Document review','Visual inspection','Electrical inspection / testing','Functional testing','Packing / preservation'],array['Documentation','Cell / module condition','Connections','BMS / controls','Capacity / performance','Packing / preservation','Test result'],array['Incoming material review','Factory acceptance test','Capacity test','Final inspection'],array['Data sheets','Certificates','Test procedures','Test reports','Shipping / storage requirements']),
('BUSWAY','Busway / Bus Duct','Electrical',array['Document review','Visual inspection','Dimensional inspection','Electrical inspection / testing','Final inspection'],array['Documentation','Dimensions / fit-up','Busbar','Insulation','Joints / connections','Enclosure / coating','Test result'],array['In-process surveillance','Electrical test','Final inspection','Shipment release'],array['Approved drawings','Data sheets','Test procedure','Test reports']),
('CHILLER','Chiller','Mechanical',array['Document review','Material identification / traceability','Visual inspection','Pressure / hydrostatic testing','Functional testing','Final inspection'],array['Documentation','Pressure boundary','Piping / tubing','Refrigerant system','Controls','Electrical','Leaks','Performance / test result'],array['Pressure test','Factory acceptance test','Performance test','Final inspection','Shipment release'],array['Approved drawings','Data sheets','Pressure test records','FAT procedure','Performance test report']),
('PUMP','Pump','Rotating Equipment',array['Document review','Material identification / traceability','Visual inspection','Dimensional inspection','Functional testing','Final inspection'],array['Documentation','Materials','Dimensions','Alignment / runout','Vibration','Performance','Mechanical seal','Test result'],array['Material review','Dimensional inspection','Performance test','Mechanical run test','Final inspection'],array['Approved drawings','Data sheets','Material certificates','Test procedures','Performance curves','Test reports']),
('HEAT_EXCHANGER','Heat Exchanger','Static Equipment',array['Document review','Material identification / traceability','Welding inspection','NDE/NDT witnessing','Pressure / hydrostatic testing','Final inspection'],array['Documentation','Materials / traceability','Welding','NDE','Dimensions','Pressure test','Tube / bundle','Coating / preservation'],array['Material identification','Welding / NDE','Pressure test','Final inspection','Shipment release'],array['Approved drawings','Material certificates','WPS/PQR','NDE reports','Pressure test certificate','Data book']),
('PRESSURE_VESSEL','Pressure Vessel','Static Equipment',array['Document review','Material identification / traceability','Welding inspection','NDE/NDT witnessing','Pressure / hydrostatic testing','Coating / painting inspection','Final inspection'],array['Documentation','Materials / traceability','Welding','NDE','Dimensions','Pressure test','Nozzles / attachments','Coating'],array['Material identification','Fit-up / welding','NDE','Pressure test','Final inspection','Shipment release'],array['Approved drawings','Material certificates','WPS/PQR','Welder qualifications','NDE reports','Pressure test certificate','Data book']),
('CONTROL_PANEL','Control Panel','Instrumentation / Electrical',array['Document review','Visual inspection','Electrical inspection / testing','Functional testing','Final inspection'],array['Documentation','Wiring / terminations','Components','Labeling','PLC / controls','Enclosure','Functional test'],array['Panel inspection','I/O / functional test','Factory acceptance test','Final inspection'],array['Approved drawings','Schematics','I/O list','FAT procedure','Test report']),
('PACKAGED_SKID','Packaged Equipment / Skid','Multi-discipline',array['Document review','Material identification / traceability','Visual inspection','Dimensional inspection','Welding inspection','NDE/NDT witnessing','Pressure / hydrostatic testing','Functional testing','Electrical inspection / testing','Final inspection'],array['Documentation','Materials','Welding / NDE','Piping','Mechanical equipment','Electrical','Instrumentation','Coating','Functional test'],array['In-process surveillance','Pressure test','Functional test / FAT','Final inspection','Shipment release'],array['Approved drawings','P&IDs','Material certificates','Welding/NDE records','Test procedures','FAT report','Data book'])
on conflict(family_code) do nothing;

alter table public.assets add column if not exists equipment_family_code text references public.equipment_families(family_code);
alter table public.assets add column if not exists model_number text;
alter table public.assets add column if not exists factory_location text;
alter table public.assets add column if not exists commodity_description text;
alter table public.inspection_reports add column if not exists equipment_family_code text references public.equipment_families(family_code);
