"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase";

type EventRow={id:string;title:string;company_name:string|null;project_name:string|null;location:string|null;starts_at:string;ends_at:string;event_type:string;source:string};
type Credential={id:string;credential_name:string;expires_on:string|null;reminder_days:number};

function overlaps(aStart:string,aEnd:string,bStart:string,bEnd:string){return new Date(aStart)<new Date(bEnd)&&new Date(aEnd)>new Date(bStart)}

export default function InspectorSchedulePage(){
 const supabase=useMemo(()=>supabaseBrowser(),[]); const [events,setEvents]=useState<EventRow[]>([]); const [credentials,setCredentials]=useState<Credential[]>([]); const [msg,setMsg]=useState(""); const [conflicts,setConflicts]=useState<string[]>([]);
 useEffect(()=>{void load()},[]);
 async function load(){const {data:a}=await supabase.auth.getUser();if(!a.user){setMsg("Log in to use InspectorHub Scheduling.");return;}const [er,cr]=await Promise.all([supabase.from("inspector_schedule_events").select("id,title,company_name,project_name,location,starts_at,ends_at,event_type,source").eq("inspector_id",a.user.id).order("starts_at"),supabase.from("inspector_credentials").select("id,credential_name,expires_on,reminder_days").eq("inspector_id",a.user.id).order("expires_on")]);if(er.error||cr.error)setMsg(er.error?.message||cr.error?.message||"");setEvents((er.data||[]) as EventRow[]);setCredentials((cr.data||[]) as Credential[])}
 async function addEvent(e:FormEvent<HTMLFormElement>){e.preventDefault();const {data:a}=await supabase.auth.getUser();if(!a.user)return;const f=new FormData(e.currentTarget);const starts=String(f.get("starts_at"));const ends=String(f.get("ends_at"));const hits=events.filter(x=>overlaps(starts,ends,x.starts_at,x.ends_at));setConflicts(hits.map(x=>`${x.title} (${new Date(x.starts_at).toLocaleString()}–${new Date(x.ends_at).toLocaleString()})`));if(hits.length){setMsg("Potential scheduling conflict detected. Review before saving.");return;}const {error}=await supabase.from("inspector_schedule_events").insert({inspector_id:a.user.id,title:f.get("title"),company_name:f.get("company_name"),project_name:f.get("project_name"),location:f.get("location"),starts_at:starts,ends_at:ends,event_type:f.get("event_type"),notes:f.get("notes")});setMsg(error?error.message:"Schedule event added.");if(!error){e.currentTarget.reset();setConflicts([]);await load()}}
 async function addCredential(e:FormEvent<HTMLFormElement>){e.preventDefault();const {data:a}=await supabase.auth.getUser();if(!a.user)return;const f=new FormData(e.currentTarget);const {error}=await supabase.from("inspector_credentials").insert({inspector_id:a.user.id,credential_name:f.get("credential_name"),credential_number:f.get("credential_number"),issuer:f.get("issuer"),expires_on:f.get("expires_on")||null,reminder_days:Number(f.get("reminder_days")||30)});setMsg(error?error.message:"Credential reminder added.");if(!error){e.currentTarget.reset();await load()}}
 async function importICS(file:File){const {data:a}=await supabase.auth.getUser();if(!a.user)return;const text=await file.text();const blocks=text.split("BEGIN:VEVENT").slice(1).map(x=>x.split("END:VEVENT")[0]);const rows=blocks.map((b,i)=>{const lines=b.split(/\r?\n/);const get=(k:string)=>lines.find(l=>l.startsWith(k+":"))?.slice(k.length+1)||"";const parse=(v:string)=>{if(/^\d{8}T\d{6}Z$/.test(v))return new Date(v.replace(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z$/,"$1-$2-$3T$4:$5:$6Z")).toISOString();if(/^\d{8}T\d{6}$/.test(v))return new Date(v.replace(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})$/,"$1-$2-$3T$4:$5:$6")).toISOString();return ""};return{inspector_id:a.user!.id,title:get("SUMMARY")||`Imported event ${i+1}`,location:get("LOCATION")||null,starts_at:parse(get("DTSTART")),ends_at:parse(get("DTEND")),event_type:"other",source:"ics",external_uid:get("UID")||null}}).filter(r=>r.starts_at&&r.ends_at);if(!rows.length){setMsg("No importable events were found in that ICS file.");return;}const {error}=await supabase.from("inspector_schedule_events").insert(rows);setMsg(error?error.message:`Imported ${rows.length} calendar event(s).`);if(!error)await load()}
 function exportICS(){const esc=(s:string)=>s.replace(/[,;\\]/g,m=>"\\"+m).replace(/\n/g,"\\n");const dt=(s:string)=>new Date(s).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");const body=events.map(e=>`BEGIN:VEVENT\r\nUID:${e.id}@inspectsource\r\nDTSTAMP:${dt(new Date().toISOString())}\r\nDTSTART:${dt(e.starts_at)}\r\nDTEND:${dt(e.ends_at)}\r\nSUMMARY:${esc(e.title)}\r\nLOCATION:${esc(e.location||"")}\r\nDESCRIPTION:${esc([e.company_name,e.project_name,e.source].filter(Boolean).join(" | "))}\r\nEND:VEVENT`).join("\r\n");const blob=new Blob([`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//InspectSource//InspectorHub//EN\r\n${body}\r\nEND:VCALENDAR\r\n`],{type:"text/calendar"});const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download="inspectsource-schedule.ics";a.click();URL.revokeObjectURL(u)}
 const upcomingCredentials=credentials.filter(c=>c.expires_on&&new Date(c.expires_on).getTime()-Date.now()<=Math.max(c.reminder_days,0)*86400000);
 return <main className="page"><section className="hero"><p className="eyebrow">InspectorHub</p><h1>Scheduling & Availability</h1><p>Your independent calendar across InspectSource and every other company you work for.</p></section>{msg&&<p className="notice">{msg}</p>}{conflicts.length>0&&<section className="warning"><strong>Conflicts found</strong>{conflicts.map(x=><div key={x}>{x}</div>)}</section>}
 <div className="grid"><section className="card"><h2>Add Schedule Event</h2><form onSubmit={addEvent}><Input n="title" l="Assignment / event" req/><Input n="company_name" l="Company / employer"/><Input n="project_name" l="Project"/><Input n="location" l="Location"/><label>Start<input name="starts_at" type="datetime-local" required/></label><label>End<input name="ends_at" type="datetime-local" required/></label><label>Type<select name="event_type" defaultValue="work"><option>work</option><option>travel</option><option>personal</option><option>unavailable</option><option>credential</option><option>other</option></select></label><label>Notes<textarea name="notes"/></label><button>Add to Schedule</button></form></section>
 <section className="card"><h2>Calendar Interchange</h2><p className="muted">Free standards-based integration for Google Calendar, Outlook, Apple Calendar and other ICS-compatible calendars.</p><label className="upload">Import ICS<input type="file" accept=".ics,text/calendar" onChange={e=>e.target.files?.[0]&&void importICS(e.target.files[0])}/></label><button onClick={exportICS}>Export My Schedule (.ics)</button><p className="muted">Direct Google/Outlook account sync will be a later integration layer.</p><h3>Credential reminder</h3><form onSubmit={addCredential}><Input n="credential_name" l="Credential" req/><Input n="credential_number" l="Number"/><Input n="issuer" l="Issuer"/><label>Expires<input name="expires_on" type="date"/></label><label>Remind me this many days before<input name="reminder_days" type="number" defaultValue="30" min="0"/></label><button>Add Reminder</button></form></section></div>
 <section className="card"><h2>Upcoming Schedule</h2>{events.map(e=><article className="event" key={e.id}><div><strong>{e.title}</strong><span>{e.company_name||e.project_name||e.location||"Personal schedule"}</span></div><div>{new Date(e.starts_at).toLocaleString()}<br/>to {new Date(e.ends_at).toLocaleString()}</div><b>{e.event_type}</b></article>)}{events.length===0&&<p className="muted">No schedule events yet.</p>}</section>
 <section className="card"><h2>Credential Alerts</h2>{upcomingCredentials.map(c=><article className="alert" key={c.id}><strong>{c.credential_name}</strong><span>Expires {c.expires_on}</span></article>)}{upcomingCredentials.length===0&&<p className="muted">No credentials currently inside their reminder window.</p>}</section>
 <style jsx>{`.page{max-width:1120px;margin:auto;padding:30px 18px 70px}.hero,.card{border:1px solid #e2e8f0;border-radius:18px;background:#fff}.hero{padding:28px;margin-bottom:16px}.eyebrow{font-size:.76rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.hero h1{margin:4px 0}.hero p,.muted{color:#64748b}.notice,.warning{padding:14px;border-radius:10px;margin:12px 0}.notice{background:#f1f5f9}.warning{background:#fff7ed;border:1px solid #fed7aa}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.card{padding:22px;margin-bottom:16px}.card h2{margin-top:0}form,label{display:grid;gap:6px}form{gap:10px}input,select,textarea{padding:11px;border:1px solid #cbd5e1;border-radius:9px;font:inherit}textarea{min-height:80px}button,.upload{padding:12px;border:0;border-radius:9px;background:#0f172a;color:#fff;font-weight:800;cursor:pointer}.upload input{background:#fff;color:#111827;margin-top:8px}.event{display:grid;grid-template-columns:2fr 2fr auto;gap:14px;padding:13px 0;border-top:1px solid #e2e8f0}.event div:first-child{display:grid}.event span{color:#64748b}.event b{text-transform:capitalize}.alert{display:flex;justify-content:space-between;padding:11px 0;border-top:1px solid #e2e8f0}@media(max-width:760px){.grid{grid-template-columns:1fr}.event{grid-template-columns:1fr}.alert{display:grid;gap:4px}input,select,textarea{font-size:16px}}`}</style></main>}
function Input({n,l,req=false}:{n:string;l:string;req?:boolean}){return <label>{l}<input name={n} required={req}/></label>}
