"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { supabaseBrowser } from "@/lib/supabase";

type EventRow={id:string;title:string;company_name:string|null;project_name:string|null;location:string|null;starts_at:string;ends_at:string;event_type:string;source:string;base_day_rate:number|null;weekend_premium_percent:number|null};
type Credential={id:string;credential_name:string;expires_on:string|null;reminder_days:number};
type Pref={travel_buffer_hours:number;weekend_premium_percent:number;saturday_premium_enabled:boolean;sunday_premium_enabled:boolean};
type Weekly={weekday:number;available:boolean;start_time:string|null;end_time:string|null};
const DAYS=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
function overlaps(aStart:string,aEnd:string,bStart:string,bEnd:string){return new Date(aStart)<new Date(bEnd)&&new Date(aEnd)>new Date(bStart)}
function weekendDays(start:string,end:string){let n=0;const d=new Date(start),z=new Date(end);d.setHours(0,0,0,0);while(d<z){if(d.getDay()===0||d.getDay()===6)n++;d.setDate(d.getDate()+1)}return n}

export default function InspectorSchedulePage(){
 const supabase=useMemo(()=>supabaseBrowser(),[]); const [events,setEvents]=useState<EventRow[]>([]); const [credentials,setCredentials]=useState<Credential[]>([]); const [weekly,setWeekly]=useState<Weekly[]>([]); const [pref,setPref]=useState<Pref>({travel_buffer_hours:4,weekend_premium_percent:25,saturday_premium_enabled:true,sunday_premium_enabled:true}); const [msg,setMsg]=useState(""); const [conflicts,setConflicts]=useState<string[]>([]); const [month,setMonth]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)});
 useEffect(()=>{void load()},[]);
 async function load(){const {data:a}=await supabase.auth.getUser();if(!a.user){setMsg("Log in to use InspectorHub Scheduling.");return;}const [er,cr,pr,wr]=await Promise.all([supabase.from("inspector_schedule_events").select("id,title,company_name,project_name,location,starts_at,ends_at,event_type,source,base_day_rate,weekend_premium_percent").eq("inspector_id",a.user.id).order("starts_at"),supabase.from("inspector_credentials").select("id,credential_name,expires_on,reminder_days").eq("inspector_id",a.user.id).order("expires_on"),supabase.from("inspector_availability_preferences").select("travel_buffer_hours,weekend_premium_percent,saturday_premium_enabled,sunday_premium_enabled").eq("inspector_id",a.user.id).maybeSingle(),supabase.from("inspector_weekly_availability").select("weekday,available,start_time,end_time").eq("inspector_id",a.user.id).order("weekday")]);if(er.error||cr.error||pr.error||wr.error)setMsg(er.error?.message||cr.error?.message||pr.error?.message||wr.error?.message||"");setEvents((er.data||[]) as EventRow[]);setCredentials((cr.data||[]) as Credential[]);if(pr.data)setPref(pr.data as Pref);setWeekly((wr.data||[]) as Weekly[])}
 async function savePreferences(e:FormEvent<HTMLFormElement>){e.preventDefault();const {data:a}=await supabase.auth.getUser();if(!a.user)return;const f=new FormData(e.currentTarget);const next={inspector_id:a.user.id,travel_buffer_hours:Number(f.get("travel_buffer_hours")||4),weekend_premium_percent:Number(f.get("weekend_premium_percent")||25),saturday_premium_enabled:f.get("sat")==="on",sunday_premium_enabled:f.get("sun")==="on",updated_at:new Date().toISOString()};const {error}=await supabase.from("inspector_availability_preferences").upsert(next);setMsg(error?error.message:"Availability intelligence settings saved.");if(!error){setPref(next);await load()}}
 async function saveWeekly(e:FormEvent<HTMLFormElement>){e.preventDefault();const {data:a}=await supabase.auth.getUser();if(!a.user)return;const f=new FormData(e.currentTarget);const rows=DAYS.map((_,weekday)=>({inspector_id:a.user!.id,weekday,available:f.get(`day-${weekday}`)==="on",start_time:String(f.get(`start-${weekday}`)||"")||null,end_time:String(f.get(`end-${weekday}`)||"")||null,updated_at:new Date().toISOString()}));const {error}=await supabase.from("inspector_weekly_availability").upsert(rows,{onConflict:"inspector_id,weekday"});setMsg(error?error.message:"Recurring weekly availability saved.");if(!error)await load()}
 async function addEvent(e:FormEvent<HTMLFormElement>){e.preventDefault();const {data:a}=await supabase.auth.getUser();if(!a.user)return;const f=new FormData(e.currentTarget);const starts=String(f.get("starts_at"));const ends=String(f.get("ends_at"));const buffer=pref.travel_buffer_hours*3600000;const bs=new Date(new Date(starts).getTime()-buffer).toISOString(),be=new Date(new Date(ends).getTime()+buffer).toISOString();const hits=events.filter(x=>overlaps(bs,be,x.starts_at,x.ends_at));setConflicts(hits.map(x=>`${x.title} (${new Date(x.starts_at).toLocaleString()}–${new Date(x.ends_at).toLocaleString()})`));if(hits.length){setMsg(`Potential conflict detected including the ${pref.travel_buffer_hours}h travel buffer.`);return;}const w=weekendDays(starts,ends);const base=Number(f.get("base_day_rate")||0)||null;const {error}=await supabase.from("inspector_schedule_events").insert({inspector_id:a.user.id,title:f.get("title"),company_name:f.get("company_name"),project_name:f.get("project_name"),location:f.get("location"),starts_at:starts,ends_at:ends,event_type:f.get("event_type"),notes:f.get("notes"),travel_buffer_before_hours:pref.travel_buffer_hours,travel_buffer_after_hours:pref.travel_buffer_hours,billable:f.get("billable")==="on",base_day_rate:base,weekend_premium_percent:w?pref.weekend_premium_percent:null});setMsg(error?error.message:w?`Schedule event added. Weekend Premium applies to ${w} day(s).`:"Schedule event added.");if(!error){e.currentTarget.reset();setConflicts([]);await load()}}
 async function addCredential(e:FormEvent<HTMLFormElement>){e.preventDefault();const {data:a}=await supabase.auth.getUser();if(!a.user)return;const f=new FormData(e.currentTarget);const {error}=await supabase.from("inspector_credentials").insert({inspector_id:a.user.id,credential_name:f.get("credential_name"),credential_number:f.get("credential_number"),issuer:f.get("issuer"),expires_on:f.get("expires_on")||null,reminder_days:Number(f.get("reminder_days")||30)});setMsg(error?error.message:"Credential reminder added.");if(!error){e.currentTarget.reset();await load()}}
 async function importICS(file:File){const {data:a}=await supabase.auth.getUser();if(!a.user)return;const text=await file.text();const blocks=text.split("BEGIN:VEVENT").slice(1).map(x=>x.split("END:VEVENT")[0]);const rows=blocks.map((b,i)=>{const lines=b.split(/\r?\n/);const get=(k:string)=>lines.find(l=>l.startsWith(k+":"))?.slice(k.length+1)||"";const parse=(v:string)=>/^\d{8}T\d{6}Z?$/.test(v)?new Date(v.replace(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})Z?$/,"$1-$2-$3T$4:$5:$6Z")).toISOString():"";return{inspector_id:a.user!.id,title:get("SUMMARY")||`Imported event ${i+1}`,location:get("LOCATION")||null,starts_at:parse(get("DTSTART")),ends_at:parse(get("DTEND")),event_type:"other",source:"ics",external_uid:get("UID")||null}}).filter(r=>r.starts_at&&r.ends_at);if(!rows.length){setMsg("No importable events were found in that ICS file.");return;}const {error}=await supabase.from("inspector_schedule_events").insert(rows);setMsg(error?error.message:`Imported ${rows.length} calendar event(s).`);if(!error)await load()}
 function exportICS(){const esc=(s:string)=>s.replace(/[,;\\]/g,m=>"\\"+m).replace(/\n/g,"\\n");const dt=(s:string)=>new Date(s).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}/,"");const body=events.map(e=>`BEGIN:VEVENT\r\nUID:${e.id}@inspectsource\r\nDTSTAMP:${dt(new Date().toISOString())}\r\nDTSTART:${dt(e.starts_at)}\r\nDTEND:${dt(e.ends_at)}\r\nSUMMARY:${esc(e.title)}\r\nLOCATION:${esc(e.location||"")}\r\nDESCRIPTION:${esc([e.company_name,e.project_name,e.source].filter(Boolean).join(" | "))}\r\nEND:VEVENT`).join("\r\n");const blob=new Blob([`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//InspectSource//InspectorHub//EN\r\n${body}\r\nEND:VCALENDAR\r\n`],{type:"text/calendar"});const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download="inspectsource-schedule.ics";a.click();URL.revokeObjectURL(u)}
 const upcomingCredentials=credentials.filter(c=>c.expires_on&&new Date(c.expires_on).getTime()-Date.now()<=Math.max(c.reminder_days,0)*86400000);
 const cells=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1);const start=new Date(first);start.setDate(1-first.getDay());return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const dayEvents=events.filter(e=>{const s=new Date(e.starts_at),z=new Date(e.ends_at);return d>=new Date(s.getFullYear(),s.getMonth(),s.getDate())&&d<=new Date(z.getFullYear(),z.getMonth(),z.getDate())});return{d,dayEvents}})},[month,events]);
 return <main className="page"><section className="hero"><p className="eyebrow">InspectorHub</p><h1>Availability Intelligence</h1><p>Your independent schedule, pricing signals and availability across every company you work for.</p></section>{msg&&<p className="notice">{msg}</p>}{conflicts.length>0&&<section className="warning"><strong>Conflicts found</strong>{conflicts.map(x=><div key={x}>{x}</div>)}</section>}
 <section className="premium"><div><p className="eyebrow">Highlighted commercial rule</p><h2>Weekend Premium</h2><p>Saturday/Sunday work is automatically flagged for premium pricing.</p></div><strong>+{pref.weekend_premium_percent}%</strong></section>
 <div className="grid"><section className="card"><h2>Availability Settings</h2><form onSubmit={savePreferences}><label>Travel buffer before/after assignments (hours)<input name="travel_buffer_hours" type="number" min="0" max="72" step=".5" defaultValue={pref.travel_buffer_hours}/></label><label>Weekend premium %<input name="weekend_premium_percent" type="number" min="0" max="300" step="1" defaultValue={pref.weekend_premium_percent}/></label><div className="checkrow"><label><input name="sat" type="checkbox" defaultChecked={pref.saturday_premium_enabled}/> Saturday premium</label><label><input name="sun" type="checkbox" defaultChecked={pref.sunday_premium_enabled}/> Sunday premium</label></div><button>Save Settings</button></form></section>
 <section className="card"><h2>Recurring Weekly Availability</h2><form onSubmit={saveWeekly}>{DAYS.map((d,i)=>{const r=weekly.find(x=>x.weekday===i);return <div className="weekly" key={d}><label><input name={`day-${i}`} type="checkbox" defaultChecked={r?r.available:i>0&&i<6}/>{d}</label><input name={`start-${i}`} type="time" defaultValue={r?.start_time?.slice(0,5)||"08:00"}/><input name={`end-${i}`} type="time" defaultValue={r?.end_time?.slice(0,5)||"17:00"}/></div>})}<button>Save Weekly Pattern</button></form></section></div>
 <section className="card"><div className="calhead"><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><h2>{month.toLocaleString(undefined,{month:"long",year:"numeric"})}</h2><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></div><div className="weeknames">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><b key={x}>{x}</b>)}</div><div className="calendar">{cells.map(({d,dayEvents},i)=>{const weekend=d.getDay()===0||d.getDay()===6;return <div className={`day ${d.getMonth()!==month.getMonth()?"mutedday":""} ${weekend?"weekend":""}`} key={i}><strong>{d.getDate()}</strong>{weekend&&<em>PREMIUM</em>}{dayEvents.slice(0,3).map(e=><span key={e.id}>{e.title}</span>)}</div>})}</div></section>
 <div className="grid"><section className="card"><h2>Add Schedule Event</h2><form onSubmit={addEvent}><Input n="title" l="Assignment / event" req/><Input n="company_name" l="Company / employer"/><Input n="project_name" l="Project"/><Input n="location" l="Location"/><label>Start<input name="starts_at" type="datetime-local" required/></label><label>End<input name="ends_at" type="datetime-local" required/></label><label>Type<select name="event_type" defaultValue="work"><option>work</option><option>travel</option><option>personal</option><option>unavailable</option><option>credential</option><option>other</option></select></label><Input n="base_day_rate" l="Base day rate (optional)" t="number"/><label><input name="billable" type="checkbox"/> Billable assignment</label><label>Notes<textarea name="notes"/></label><button>Add to Schedule</button></form></section>
 <section className="card"><h2>Calendar Interchange</h2><p className="muted">Free standards-based integration for Google Calendar, Outlook, Apple Calendar and other ICS-compatible calendars.</p><label className="upload">Import ICS<input type="file" accept=".ics,text/calendar" onChange={e=>e.target.files?.[0]&&void importICS(e.target.files[0])}/></label><button onClick={exportICS}>Export My Schedule (.ics)</button><h3>Credential reminder</h3><form onSubmit={addCredential}><Input n="credential_name" l="Credential" req/><Input n="credential_number" l="Number"/><Input n="issuer" l="Issuer"/><label>Expires<input name="expires_on" type="date"/></label><label>Remind me this many days before<input name="reminder_days" type="number" defaultValue="30" min="0"/></label><button>Add Reminder</button></form></section></div>
 <section className="card"><h2>Upcoming Schedule</h2>{events.map(e=>{const w=weekendDays(e.starts_at,e.ends_at);return <article className="event" key={e.id}><div><strong>{e.title}</strong><span>{e.company_name||e.project_name||e.location||"Personal schedule"}</span></div><div>{new Date(e.starts_at).toLocaleString()}<br/>to {new Date(e.ends_at).toLocaleString()}</div><div><b>{e.event_type}</b>{w>0&&<mark>Weekend Premium +{e.weekend_premium_percent??pref.weekend_premium_percent}%</mark>}</div></article>})}{events.length===0&&<p className="muted">No schedule events yet.</p>}</section>
 <section className="card"><h2>Credential Alerts</h2>{upcomingCredentials.map(c=><article className="alert" key={c.id}><strong>{c.credential_name}</strong><span>Expires {c.expires_on}</span></article>)}{upcomingCredentials.length===0&&<p className="muted">No credentials currently inside their reminder window.</p>}</section>
 <style jsx>{`.page{max-width:1180px;margin:auto;padding:30px 18px 70px}.hero,.card,.premium{border:1px solid #e2e8f0;border-radius:18px;background:#fff}.hero{padding:28px;margin-bottom:16px}.eyebrow{font-size:.76rem;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.hero h1{margin:4px 0}.hero p,.muted{color:#64748b}.notice,.warning{padding:14px;border-radius:10px;margin:12px 0}.notice{background:#f1f5f9}.warning{background:#fff7ed;border:1px solid #fed7aa}.premium{display:flex;justify-content:space-between;align-items:center;padding:22px;margin-bottom:16px;background:#fffbeb;border:2px solid #f59e0b}.premium h2{margin:2px 0}.premium strong{font-size:2.4rem;color:#92400e}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.card{padding:22px;margin-bottom:16px}.card h2{margin-top:0}form,label{display:grid;gap:6px}form{gap:10px}input,select,textarea{padding:11px;border:1px solid #cbd5e1;border-radius:9px;font:inherit}textarea{min-height:80px}button,.upload{padding:12px;border:0;border-radius:9px;background:#0f172a;color:#fff;font-weight:800;cursor:pointer}.checkrow{display:flex;gap:16px}.checkrow label{display:flex;align-items:center}.weekly{display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:8px;align-items:center}.weekly label{display:flex;align-items:center;gap:6px}.calhead{display:flex;justify-content:space-between;align-items:center}.calhead button{padding:8px 14px}.weeknames,.calendar{display:grid;grid-template-columns:repeat(7,1fr)}.weeknames b{text-align:center;padding:8px}.day{min-height:105px;border:1px solid #e2e8f0;padding:7px;display:flex;flex-direction:column;gap:4px}.day span{font-size:.72rem;background:#f1f5f9;padding:3px;border-radius:4px}.day em{font-size:.6rem;font-style:normal;font-weight:900;color:#92400e}.weekend{background:#fffbeb}.mutedday{opacity:.42}.upload input{background:#fff;color:#111827;margin-top:8px}.event{display:grid;grid-template-columns:2fr 2fr 1fr;gap:14px;padding:13px 0;border-top:1px solid #e2e8f0}.event div:first-child{display:grid}.event span{color:#64748b}.event b{text-transform:capitalize}.event div:last-child{display:grid;gap:6px}.event mark{background:#fef3c7;color:#92400e;padding:4px 7px;border-radius:6px;font-size:.72rem;font-weight:800}.alert{display:flex;justify-content:space-between;padding:11px 0;border-top:1px solid #e2e8f0}@media(max-width:760px){.grid{grid-template-columns:1fr}.premium{align-items:flex-start}.premium strong{font-size:1.8rem}.weekly{grid-template-columns:1fr 1fr 1fr}.day{min-height:70px;padding:4px}.day span{display:none}.event{grid-template-columns:1fr}.alert{display:grid;gap:4px}input,select,textarea{font-size:16px}}`}</style></main>}
function Input({n,l,req=false,t="text"}:{n:string;l:string;req?:boolean;t?:string}){return <label>{l}<input name={n} required={req} type={t}/></label>}
