"use client";

import { useMemo, useState } from "react";

type Report={id:string;client:string;industry:string;commodity:string;submitted:string;title:string;location:string;summary:string};

const REPORTS:Report[]=[
{id:"IR-260918",client:"Northstar Energy",industry:"Oil & Gas",commodity:"Piping",submitted:"2026-09-18",title:"Piping fabrication surveillance",location:"Houston, USA",summary:"Final dimensional, material traceability and documentation review completed."},
{id:"IR-260914",client:"Bluewater LNG",industry:"LNG",commodity:"Compressors",submitted:"2026-09-14",title:"Compressor package FAT",location:"Busan, South Korea",summary:"FAT witness completed with release dossier observations recorded."},
{id:"IR-260909",client:"Aurora Renewables",industry:"Offshore Wind",commodity:"Structural Steel",submitted:"2026-09-09",title:"Transition piece welding surveillance",location:"Newcastle, UK",summary:"Welding surveillance and NDT record review completed."},
{id:"IR-260902",client:"Northstar Energy",industry:"Refining",commodity:"Pressure Vessels",submitted:"2026-09-02",title:"Pressure vessel final inspection",location:"Texas, USA",summary:"Final visual, dimensional and nameplate verification completed."},
{id:"IR-260827",client:"Meridian Power",industry:"Power",commodity:"Transformers",submitted:"2026-08-27",title:"Transformer FAT witness",location:"Monterrey, Mexico",summary:"Routine and dielectric test witnessing completed against approved ITP."},
{id:"IR-260821",client:"Bluewater LNG",industry:"LNG",commodity:"Valves",submitted:"2026-08-21",title:"Cryogenic valve inspection",location:"Milan, Italy",summary:"Material, pressure-test and documentation checkpoints completed."},
{id:"IR-260815",client:"Atlas Petrochem",industry:"Petrochemical",commodity:"Heat Exchangers",submitted:"2026-08-15",title:"Heat exchanger final inspection",location:"Rotterdam, Netherlands",summary:"Final inspection and MDR review completed before release."},
{id:"IR-260808",client:"Meridian Power",industry:"Power",commodity:"Rotating Equipment",submitted:"2026-08-08",title:"Pump package FAT",location:"Houston, USA",summary:"Performance-test witnessing and preservation review completed."},
{id:"IR-260731",client:"Harbor Offshore",industry:"Offshore",commodity:"Lifting Equipment",submitted:"2026-07-31",title:"Lifting equipment inspection",location:"Aberdeen, UK",summary:"Certification, marking and functional inspection completed."},
{id:"IR-260724",client:"Atlas Petrochem",industry:"Petrochemical",commodity:"Piping",submitted:"2026-07-24",title:"Shop piping surveillance",location:"Pune, India",summary:"Welding, NDT and traceability surveillance completed."},
{id:"IR-260718",client:"Northstar Energy",industry:"Oil & Gas",commodity:"Coatings",submitted:"2026-07-18",title:"Protective coating inspection",location:"Louisiana, USA",summary:"Surface preparation and coating application checkpoints completed."},
{id:"IR-260710",client:"Aurora Renewables",industry:"Offshore Wind",commodity:"Electrical",submitted:"2026-07-10",title:"Electrical panel FAT",location:"Hamburg, Germany",summary:"Functional checks and documentation review completed."}
];

export default function InspectorReportsDemo(){
 const [client,setClient]=useState("All clients"); const [industry,setIndustry]=useState("All industries"); const [commodity,setCommodity]=useState("All commodities"); const [open,setOpen]=useState<Report|null>(null);
 const values=(key:"client"|"industry"|"commodity"):string[]=>Array.from(new Set(REPORTS.map(r=>r[key]))).sort();
 const filtered=useMemo(()=>REPORTS.filter(r=>(client==="All clients"||r.client===client)&&(industry==="All industries"||r.industry===industry)&&(commodity==="All commodities"||r.commodity===commodity)),[client,industry,commodity]);
 return <main className="shell"><header><p className="eyebrow">InspectorHub · Synthetic demo</p><h1>Inspection Reports</h1><p>Latest submitted inspection reports for this synthetic inspector profile. Demo records only; no production report or client data is used.</p></header>
 <section className="filters" aria-label="Report filters"><label>Client<select value={client} onChange={e=>setClient(e.target.value)}><option>All clients</option>{values("client").map(x=><option key={x}>{x}</option>)}</select></label><label>Industry<select value={industry} onChange={e=>setIndustry(e.target.value)}><option>All industries</option>{values("industry").map(x=><option key={x}>{x}</option>)}</select></label><label>Commodity<select value={commodity} onChange={e=>setCommodity(e.target.value)}><option>All commodities</option>{values("commodity").map(x=><option key={x}>{x}</option>)}</select></label></section>
 <p className="count" role="status">Showing {filtered.length} of {REPORTS.length} submitted reports</p><section className="reports">{filtered.map(r=><article key={r.id}><div><strong>{r.title}</strong><span>{r.id} · Submitted {r.submitted}</span><span>{r.client} · {r.industry} · {r.commodity}</span><span>{r.location}</span></div><button type="button" onClick={()=>setOpen(r)}>Open report</button></article>)}</section>
 {open&&<div className="backdrop" onClick={()=>setOpen(null)}><section className="modal" role="dialog" aria-modal="true" aria-label={`Report ${open.id}`} onClick={e=>e.stopPropagation()}><button className="close" type="button" onClick={()=>setOpen(null)} aria-label="Close report">Close</button><p className="eyebrow">Submitted report · {open.id}</p><h2>{open.title}</h2><p><b>{open.client}</b> · {open.industry} · {open.commodity}</p><p>{open.location} · Submitted {open.submitted}</p><p>{open.summary}</p><aside>This is a synthetic report preview. It does not represent a real inspection finding, client record or production document.</aside></section></div>}
 <style jsx>{`.shell{max-width:1100px;margin:auto;padding:28px;color:#0f172a}header,.filters,.reports article{background:#fff;border:1px solid #dbe3ee;border-radius:16px}header{padding:22px}h1{margin:4px 0}.eyebrow{color:#0f766e;font-weight:900;text-transform:uppercase;letter-spacing:.1em;font-size:.72rem}.filters{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding:16px;margin:14px 0}.filters label{display:grid;gap:6px;font-weight:800;font-size:.8rem}.filters select{padding:10px;border:1px solid #64748b;border-radius:8px;background:#fff;color:#0f172a}.filters select:focus-visible,button:focus-visible{outline:3px solid #5eead4;outline-offset:2px}.count{font-weight:800}.reports{display:grid;gap:10px}.reports article{padding:15px;display:flex;justify-content:space-between;align-items:center;gap:14px}.reports article div{display:grid;gap:4px}.reports span{color:#64748b;font-size:.86rem}button{border:1px solid #0f766e;background:#0f766e;color:#fff;border-radius:9px;padding:10px 12px;font-weight:800;cursor:pointer}button:hover{background:#115e59}.backdrop{position:fixed;inset:0;background:#0f172a99;display:grid;place-items:center;padding:20px}.modal{width:min(680px,96vw);background:#fff;border-radius:18px;padding:24px}.close{float:right}.modal aside{padding:12px;background:#f0fdfa;color:#115e59;border-radius:10px}@media(max-width:700px){.filters{grid-template-columns:1fr}.reports article{align-items:stretch;flex-direction:column}}`}</style></main>;
}
