"use client";
import Link from "next/link";
import { useMemo,useState } from "react";
import ClientWorkspaceSidebar from "@/components/ClientWorkspaceSidebar";

type Channel={agency:string;rate:string;terms:string;package:string};
type Person={id:string;name:string;qualification:string;status:string;independentOptIn:boolean;channels:Channel[]};
const agencies=[
 {name:"Northstar Inspection Partners",contract:"MSA-204 · Active",coverage:"US Gulf Coast · LNG · pressure equipment",budget:"$420k annual",spend:"$286k YTD",capacity:"18 available / 62 resources"},
 {name:"Meridian Quality Services",contract:"MSA-118 · Active",coverage:"Europe · valves · rotating equipment",budget:"€310k annual",spend:"€201k YTD",capacity:"11 available / 47 resources"},
 {name:"Atlas Technical Inspection",contract:"PO Framework 77 · Active",coverage:"Middle East · refinery · pipelines",budget:"$275k annual",spend:"$164k YTD",capacity:"14 available / 55 resources"}
];
const people:Person[]=[
 {id:"IS-20418",name:"Maya Chen",qualification:"API 570 · AWS CWI · Houston",status:"Verified with 2 agencies",independentOptIn:true,channels:[{agency:"Northstar Inspection Partners",rate:"USD 1,080/day",terms:"Net 45",package:"Mileage capped · lodging separate · report time included"},{agency:"Atlas Technical Inspection",rate:"USD 1,145/day",terms:"Net 30",package:"Mileage included · lodging capped · OT +25%"}]},
 {id:"IS-11742",name:"Omar Haddad",qualification:"API 510 · API 570 · UAE/Qatar",status:"Verified with Atlas",independentOptIn:true,channels:[{agency:"Atlas Technical Inspection",rate:"USD 1,240/day",terms:"Net 30",package:"Per diem included · airfare separate · travel time 50%"}]},
 {id:"IS-39012",name:"Jordan Silva",qualification:"AWS CWI · API 570 · Houston",status:"Agency claim pending — independent remains eligible",independentOptIn:true,channels:[]},
 {id:"IS-51804",name:"Samira Costa",qualification:"API 570 · 9 years refinery · Texas",status:"Prior affiliation ended — independent resumed",independentOptIn:true,channels:[]}
];
export default function ClientAgencySourcingDemo(){
 const [source,setSource]=useState("both");
 const visible=useMemo(()=>people.filter(p=>source!=="agencies"||p.channels.length>0).filter(p=>source!=="independent"||p.channels.length===0),[source]);
 return <main className="shell"><ClientWorkspaceSidebar demo/><section className="workspace"><div className="notice"><b>Demo Mode</b> — fictional sourcing records only. No production matching, persistence, affiliation verification, or commercial routing occurs here.</div><header><div><p className="eyebrow">Client · Contracted Agencies</p><h1>Choose how to source inspectors</h1><p>Compare contracted agency capacity and commercials with independent marketplace availability while keeping one inspector identity per person.</p></div><Link href="/demo/client">← Client Demo</Link></header>
 <section className="card"><h2>Contracted Agencies</h2><div className="agencyGrid">{agencies.map(a=><article key={a.name}><b>{a.name}</b><span>{a.contract}</span><p>{a.coverage}</p><dl><dt>Budget</dt><dd>{a.budget}</dd><dt>Spend</dt><dd>{a.spend}</dd><dt>Resource availability</dt><dd>{a.capacity}</dd></dl></article>)}</div></section>
 <section className="card"><div className="sectionHead"><div><h2>Source of Inspectors</h2><p>Limit this synthetic search to contracted agencies, independents, or both.</p></div><div className="seg" role="group" aria-label="Source of Inspectors">{[["agencies","Contracted agencies only"],["independent","Independent inspectors only"],["both","Contracted agencies + independent inspectors"]].map(([v,l])=><button key={v} aria-pressed={source===v} onClick={()=>setSource(v)}>{l}</button>)}</div></div>
 <div className="rule"><b>Eligibility model preview</b><span>Any active Verified agency affiliation suppresses the Independent channel. Pending/unverified claims do not. When all Verified affiliations end, independent eligibility can resume only when the inspector opted in.</span></div>
 <div className="results">{visible.map(p=><article key={p.id}><div className="person"><div><b>{p.name}</b><small>{p.id} · {p.qualification}</small></div><span>{p.status}</span></div>{p.channels.length>0?<div className="channels">{p.channels.map(c=><div key={c.agency}><strong>{c.agency}</strong><span>{c.rate} · {c.terms}</span><small>{c.package}</small><button>Use this agency channel</button></div>)}</div>:<div className="independent"><strong>Independent inspector</strong><span>Eligible because there is no active Verified agency affiliation.</span><button>Use independent channel</button></div>}</article>)}</div>
 <p className="fine">A person appears once even when multiple agency channels are eligible. Selecting a specific agency pool attributes the opportunity to that agency; broad searches require the commercial sourcing channel to be recorded at selection. Upload order alone never creates agency ownership. This page demonstrates the rule only; production enforcement remains review-gated.</p></section>
 </section><style jsx>{`.shell{max-width:1440px;margin:auto;padding:18px;display:grid;grid-template-columns:250px minmax(0,1fr);gap:20px}.workspace{min-width:0}.notice,.card{border:1px solid #dbe3ee;border-radius:14px;background:#fff}.notice{padding:10px 14px;background:#eff6ff;color:#1e40af;margin-bottom:14px}header,.sectionHead,.person{display:flex;justify-content:space-between;gap:18px;align-items:flex-start}header h1{margin:4px 0}header p{color:#64748b}.eyebrow{text-transform:uppercase;letter-spacing:.1em;font-size:.72rem;font-weight:800;color:#0f766e}.card{padding:18px;margin-bottom:14px}.card h2{margin-top:0}.agencyGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.agencyGrid article,.results>article{border:1px solid #e2e8f0;border-radius:12px;padding:14px}.agencyGrid span,.agencyGrid p,.fine{color:#64748b;font-size:.82rem}.agencyGrid span{display:block;margin-top:4px}.agencyGrid dl{display:grid;grid-template-columns:auto 1fr;gap:5px 10px;font-size:.78rem}.agencyGrid dd{margin:0;color:#475569}.seg{display:flex;flex-wrap:wrap;gap:6px}.seg button,.channels button,.independent button{border:1px solid #cbd5e1;border-radius:8px;padding:8px 10px;background:#fff;cursor:pointer}.seg button[aria-pressed=true]{background:#0f172a;color:#fff;border-color:#0f172a}.rule{display:grid;gap:4px;background:#fffbeb;border:1px solid #fde68a;border-radius:10px;padding:12px;margin:14px 0}.rule span{color:#713f12;font-size:.84rem}.results{display:grid;gap:10px}.person small{display:block;color:#64748b;margin-top:3px}.person>span{font-size:.76rem;background:#f1f5f9;border-radius:999px;padding:5px 8px}.channels{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:10px}.channels div,.independent{display:grid;gap:5px;padding:11px;background:#f8fafc;border-radius:9px}.channels span,.channels small,.independent span{color:#64748b;font-size:.78rem}.channels button,.independent button{width:max-content;font-weight:700;color:#1d4ed8}.fine{line-height:1.5}@media(max-width:980px){.shell{grid-template-columns:1fr}.agencyGrid,.channels{grid-template-columns:1fr}.sectionHead,header{display:block}}`}</style></main>
}